### ISSUE TITLE
Can we create a TypeDecider just like the IndexDecider?

### ISSUE THREAD

**Issue by dahlsailrunner** [serilog/serilog-sinks-elasticsearch#100]
Hi -- We are using the index decider configuration and it works great.  We would *also* like to be able to determine the TypeName based on content of the LogEvent in a similar way.  We can fork the code and then create a PR with the new options - but thought it was worth asking here to see if this was something that would be considered or if some other approach would be better.

**Comment by mivano** [comment]
I think the safest way is fork and implement the desired solution. What is your use case to change type?

**Comment by dahlsailrunner** [comment]
Sorry for late reply -- I am in an enterprise and it has multiple products/websites we develop.  we want to do logging via a central api from the different apps, and want both different index AND types for the ES entries.  I'll create the fork and give it a go.

**Comment by mivano** [comment]
It is certainly possible, but if you want to differentiate between different kinds of apps, then you can also add an additional field in each app using enrichers.

**Comment by dahlsailrunner** [comment]
Thanks for input - I was able to get this to work without adding fields to the LogEvent.  If anyone is interested in code or what I had to change I can post it.  Appreciate the feedback though.
