### ISSUE TITLE
IndexDeciver - AppSettings

### ISSUE THREAD

**Issue by DinoSourcesRex** [serilog/serilog-sinks-elasticsearch#101]
Hi there.

Just wondering if there is a way to get the index decider from the app settings. Currently I had config in app settings which I have since had to move to startup to get this functionality.

This is my current code;
`var ES = new ElasticsearchSinkOptions(new Uri(ConfigurationManager.AppSettings["SeriLog.ElasticSearch.nodeUri"]))
{
    MinimumLogEventLevel = (LogEventLevel)Enum.Parse(typeof(LogEventLevel), ConfigurationManager.AppSettings["SeriLog.ElasticSearch.MinimumLogLevel"]),
    Period = TimeSpan.FromSeconds(int.Parse(ConfigurationManager.AppSettings["SeriLog.ElasticSearch.PostingPeriodSeconds"])),
    BatchPostingLimit = int.Parse(ConfigurationManager.AppSettings["SeriLog.ElasticSearch.BatchPostingLimit"]),
    TemplateName = "test-template",
    IndexFormat = "test-{0:yyyy.MM.dd}",
    IndexDecider = (@event, offset) => $"test-{@event.Level.ToString()}-{@event.Timestamp:yyyy.MM.dd}".ToLower()
};`

The problem line is the last one, `IndexDecider = (@event, offset) => $"test-{@event.Level.ToString()}-{@event.Timestamp:yyyy.MM.dd}".ToLower()`. Is there a way to put this into app settings? I prefer having my set up done there rather than in code.

**Comment by mivano** [comment]
At the moment this is not possible. There are a lot of options and only a certain set of them is available via the appSettings.

**Comment by Pzixel** [comment]
Please, add decider to the appsettings.json.

**Comment by mivano** [comment]
Old issue, cleaning up

**Comment by Pzixel** [comment]
What kind of cleanup is it? Should I create duplicates to make this feature rquest actual?

**Comment by mivano** [comment]
Just cleaning old and stale issues. Nobody picked this up as a PR and I do not have enough time to do feature request. Unfortunately not everything is simply possible using appsettings. Certainly not full delegates. IMHO you want this in code as it can be compiled anyway.

**Comment by Pzixel** [comment]
Well, in my case I had a simple case: if I have an error level i want to go into index.err-yyyy.MM.dd. Otherwise go into `index.regular-yyyy.mm`. Of course you have full control in the code only but you can have good enough solution for 90% cases. LIke

```cs
    "WriteTo": {
      "Console": {
        "Name": "Console",
        "Args": {
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {Message}{NewLine}{Exception}"
        },
        "IndexFormat": {
         "Error" : "index.err-yyyy.MM.dd",
         "Information" : "index.info-yyyy.MM.dd",
         "Other" : "index.generic-yyyy.MM.dd",
        }
      }
    },
```

**Comment by mivano** [comment]
I see your use case, however this is directly a specific example where you map the level to a string. Although not uncommon to use the level, I also saw examples of checking other property values to determine the index name. Getting this generic enough can become hard to do in a json structure.
