### ISSUE TITLE
Make file rolling frequency for durable sink configurable.

### ISSUE THREAD

**Issue by bacar** [serilog/serilog-sinks-elasticsearch#104]
Our disks keep filling with durable sink buffers. We tried reducing the buffer size, but it doesn't seem to be a circular buffer -- it just a stops writing any more part way through the day if we do that. 

I think the issue is that the `DurableElasticsearchSink` is hardcoded to roll once per day:

        // we rely on the date in the filename later!
        const string FileNameSuffix = "-{Date}.json";

The underlying [RollingFile Sink supports multiple formats](https://github.com/serilog/serilog-sinks-rollingfile/blob/dev/README.md):

- {Date} Creates a file per day. Filenames use the yyyyMMdd format.
- {Hour} Creates a file per hour. Filenames use the yyyyMMddHH format.
- {HalfHour} Creates a file per half hour. Filenames use the yyyyMMddHHmm format.

I propose that the rolling frequency be exposed as a configurable option on the elastic sink options. 

There's a slightly cryptic comment in the first line of code above -- if this just relates to the sorting that happens (for cleanup) on `GetFileSet` in the `ElasticSearchLogShipper` then it should still work.

**Comment by bacar** [comment]
NB this relates to, but the proposal seems significantly less complex than:
- https://github.com/serilog/serilog-sinks-elasticsearch/issues/27
- https://github.com/serilog/serilog-sinks-rollingfile/issues/33

**Comment by mivano** [comment]
I think the Seq buffer was the inspiration for the durable buffer in this sink. I do agree that the {date} alone might not be optimal. Care for a PR?

**Comment by mivano** [comment]
There is a lot that can be improved here. Closing this one for now.
