### ISSUE TITLE
Question: Passing Geolocation to Elasticsearch through SeriLog

### ISSUE THREAD

**Issue by Franklin89** [serilog/serilog-sinks-elasticsearch#105]
I was asking my self if it is possible to pass a geo location (lat/lon) to elasticsearch through the serilog sink? I have the latitude and longitude in code and added it to the LogContext. But how can I make sure that ElasticSearch picks it up as a geo_point?

Thanks for the support

**Comment by mivano** [comment]
Nice question, the fields will be added but the default mapping wont pick them up as a geo point. So can you pass your own template that marks the specific field names as geo_point?
