### ISSUE TITLE
Event / hook where I can check for log event size before it gets logged

### ISSUE THREAD

**Issue by rohitshrivastava04** [serilog/serilog-sinks-elasticsearch#112]
I am using serilog, and facing issue with ElasticsearchSink when a batch exceeds 10MB payload, I am on AWS ES service which restricts more than 10MB log. Is there any hook where I can check if a particular log entry is more than x bytes? I would like to skip such log events and replace it with a smaller log entry to say too big log message was generated and truncated.

**Comment by rohitshrivastava04** [comment]
Any suggestion?

**Comment by mivano** [comment]
You might be able to implement your own ElasticsearchJsonFormatter and do a check in there. When the size is more, then return your own message instead.

**Comment by mivano** [comment]
Closing for now, feel free to reopen if the suggestion is not working for you.
