### ISSUE TITLE
AWS ElasticSearch Service authorization problem

### ISSUE THREAD

**Issue by obegendi** [serilog/serilog-sinks-elasticsearch#113]
I'm using ElasticSearch service on AWS cloud. There is role-based security for ES service. Serilog can't write any log to ES service. Global Header does not work properly. What is the best practice to using ES service as log DB via serilog?

**Comment by rumatavz** [comment]
var options = new ElasticsearchSinkOptions(new Uri("https://!!!*!!!.us-east-1.aws.found.io:9243"))
            {
                ModifyConnectionSettings = x => x.BasicAuthentication("elastic", "!!!*!!!"),
                AutoRegisterTemplate = true,
                MinimumLogEventLevel = LogEventLevel.Debug
            };

This code do the trick

**Comment by KyleGobel** [comment]
The above looks like basic authentication?

I don't see any place to enable basic auth to an elasticsearch domain, I'm looking for more of an IAM roles approach, is there anyway to sign the request before sending it off to elasticsearch?

**Comment by P47Phoenix** [comment]
https://github.com/bcuff/elasticsearch-net-aws

#Serilog Sink Setup
```
  const string esUrl = "https://aws-es-thinger.us-west-1.es.amazonaws.com";
  Log.Logger = new LoggerConfiguration()
                .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri(esUrl))
                {
                    ModifyConnectionSettings = conn =>
                    {
                        var httpConnection = new AwsHttpConnection("us-east-1");
                        var pool = new SingleNodeConnectionPool(new Uri(esUrl));
                        return new ConnectionConfiguration(pool, httpConnection);
                    }
                })
                .CreateLogger();
```

**Comment by mivano** [comment]
Thanks for the pointer. Closing this one now, feel free to reopen if unclear.

**Comment by mariotacke** [comment]
@P47Phoenix, how is your example providing credentials? I'm currently trying to connect with basic credentials to an AWS hosted Elasticsearch.

**Comment by KyleGobel** [comment]
@mariotacke Here's a copy paste snippet of how i've been doing it 

```
 builder = builder.WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("awsurl"))
                {
                    ModifyConnectionSettings = conn =>
                    {
                        var httpConnection =
                            new AwsHttpConnection("us-west-2", new StaticCredentialsProvider(new AwsCredentials
                            {
                                AccessKey = "accessKey",
                                SecretKey = "secretKey"
                            }));
                        var pool = new SingleNodeConnectionPool(new Uri(options.AwsElasticSearchUrl));
                        return new ConnectionConfiguration(pool, httpConnection);
                    }
                });
```

**Comment by mariotacke** [comment]
Thanks @KyleGobel, that looks like it is using AWS credentials. I'm trying to use Basic auth credentials (for AWS hosted Elasticsearch), but it looks like it is not supported. I asked my ops guys to provide me with proper credentials.

**Comment by tillmannen** [comment]
I found this thread when my connection failed and I found out I needed to both have the AwsAccessKey and SecretKey as well as my username and password. And if anyone else finds this thread I found out that you can specify your Basic Auth in the ConnectionConfiguration and return something like

```
return new ConnectionConfiguration(pool, httpConnection)
    .BasicAuthentication(
        Configuration["Elasticsearch:Username"],
        Configuration["Elasticsearch:Password"]
    );
```
