### ISSUE TITLE
autoRegisterTemplate is not working in appsettings.json

### ISSUE THREAD

**Issue by xrkolovos** [serilog/serilog-sinks-elasticsearch#116]
I don't know where to log this issue. Here or the settings plugin. It might be an issue of this repo, i thing because settings works in a generic way.
I have this settings, but autoRegisterTemplate is always false

```
{
        // Logging to ElasticSearch
        // Note that Name is case-sensitive
        "Name": "Elasticsearch",
        "Args": {
          "nodeUris": "http://10.0.0.20:9200",
          "autoRegisterTemplate": true,
          "indexFormat": "authIndex-{0:yyyy.MM}",
          "minimumLogEventLevel": "Debug"
}
```

**Comment by Boggin** [comment]
It may not be available. 
Looking at the documentation in the main [README ](https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/README.md) the `autoRegisterTemplate` key isn't listed. 
I think it might be needed in [LoggerConfigurationElasticSearchExtensions.cs](https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs). 
It may be the reason I can't get the sink to work with my dotnet core 2.0.0 appsettings.

**Comment by mivano** [comment]
Found a solution yet? I m not that aware of the configuration/setting plugin. Did you check there already?

**Comment by herrminni** [comment]
I found, that it is possible to configure the ealasticsearch sink with appsettings.json.

But you have to use `options` instead of `Args` as name of the configuration object.

Example:
```
{
"Serilog": {
    "Using": [
      "Serilog.Sinks.Debug",
      "Serilog.Sinks.Elasticsearch" 
    ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "Debug" 
      },
      {
        "Name": "File",
        "Args": {
          "path": "_temp\\log\\log.txt"
        }
      },
      {
        "Name": "Elasticsearch",
        "options": {
          "nodeUris": "http://localhost:9200",
          "indexFormat": "index-{0:yyyy.MM}",
          "templateName": "serilog-events-template",
          "autoRegisterTemplate":  true
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
    "Properties": {
      "Application": "Sample"
    }
  }
}
```
