### ISSUE TITLE
Is there a way to delete durable mode old buffer files

### ISSUE THREAD

**Issue by asfyra** [serilog/serilog-sinks-elasticsearch#117]
As i saw from the source code  `Serilog.Sinks.RollingFile` is used for the durable mode. I wonder if there is a way to set the` retainedFileCountLimit` of RollingFile, so that old buffer files would be deleted and not having to delete them manually to free up space.

Thanks in advance
Alex

**Comment by frg** [comment]
I'm seeing that `BufferFileSizeLimitBytes `is passed directly to the rolling file sink. Maybe we can to the same with `retainedFileCountLimit`?

https://github.com/serilog/serilog-sinks-elasticsearch/blob/4c585309242778addad7a7ead770bdcd9004ad4a/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/DurableElasticSearchSink.cs#L43

**Comment by frg** [comment]
@asfyra Keep in mind that buffer files that have been shipped are deleted automatically so if your app is retaining buffer files you might want to debug your app.

**Comment by asfyra** [comment]
@frg you are absolutely right. After several days i realized that old files are deleted automatically. 
Thanks a lot :)
