### ISSUE TITLE
Allow to forget Elasticsearch shipping errors.

### ISSUE THREAD

**Issue by jose3m** [serilog/serilog-sinks-elasticsearch#119]
Hi.

In the context of a particular application, where I am using this sinks to store log events in durable mode, happens that if there is any error on my Elasticsearch server I don't want my app to have any issue of any kind because of it. If the Elastic server remains off for a long time then this sink continues saving the messages on disk and retrying to send them all: when the Elasctic server comes alive then all the messages are sent and this means consuming CPU and afecting my app at the end.
For me it is peferible to lose messages rather than assuring to save them all having a CPU consumption peak.

Could it be possible just to add a new parameter in the options to say that I prefer to lose messages rather than retrying?

It should be as easy as modifying the file "ElasticSearchLogShipper.cs" on the following peace of code:

                       `if (count > 0)
                        {
                            var response = _state.Client.Bulk<DynamicResponse>(payload);

                            if (response.Success)  // <---- here would come the change
                            {
                                WriteBookmark(bookmark, nextLineBeginsAtOffset, currentFilePath);
                                _connectionSchedule.MarkSuccess();
                            }
                            else
                            {
                                _connectionSchedule.MarkFailure();
                                SelfLog.WriteLine("Received failed ElasticSearch shipping result {0}: {1}", response.HttpStatusCode, response.OriginalException);
                                break;
                            }
                        }`

Thank vou very much for your time.
Jose

**Comment by frg** [comment]
@jose3m can you create a pr for this? I've got a similar use case.

**Comment by freeranger** [comment]
That does maketo me - you are using durable mesasaging so you don’t lose messages, but you are saying you want to lose messages in the case where elastic has gone down, which is exactly what this is to guard against.
Why not just log in non-durable mode indeed?

**Comment by frg** [comment]
@freeranger in my case I'm not using durable mode and when it fails it keeps taking up more and more memory.

An option to wither keep a max amount in memory, max memory to use or an option to ignore errors would all work.

**Comment by freeranger** [comment]
@frg that makes sense to me - could be a bug in the code if it keeps eating memory in non durable mode.   It was the idea of a durable mode that could lose messages that seemed like a strange idea!

**Comment by frg** [comment]
@freeranger I do agree with you on that re the durable mode. I'll create a separate issue and link to a test.

**Comment by mivano** [comment]
The durable option is indeed to make sure that when the ES server has connectivity issues, the data will be buffered and send again at a later time. It is not perfect and has its challenges. Let me know what you find out, tx.

**Comment by nblumhardt** [comment]
Howdy, friends :-)

@mivano a couple of related issues have come through the Seq sink, and recent changes improve behavior in both durable and non-durable scenarios. Just making some notes here for you, in case it's useful.

First, in **non-durable** mode, the Seq sink now accepts a `queueSizeLimit`:

https://github.com/serilog/serilog-sinks-seq/blob/dev/src/Serilog.Sinks.Seq/SeqLoggerConfigurationExtensions.cs#L82

This caps the number of events that will be buffered in memory, to avoid unpredictable memory usage. The feature is actually implemented under-the-hood by _Serilog.Sinks.PeriodicBatching_, so should be easy to integrate into the ES sink if it hasn't been done already.

Second, in **durable** mode, it's now possible to limit the amount of disk space the buffer files can consume, instead of just limiting the buffered data per day. This one is quite recent:

https://github.com/serilog/serilog-sinks-seq/pull/92

There's more information in the PR on how it's implemented.

Hope this helps!

**Comment by mivano** [comment]
Thanks @nblumhardt. Will have a look at it. My biggest concern with the current implementation is that the durable sink implements its own logic again to submit items to ES. So a lot of duplication.

**Comment by jose3m** [comment]
Hi all.

@mivano 
@nblumhardt 
You are rigth, the main scenario for the durable messaging is precisely not to lose any message, and so we normally use this sink for, but in some special cases were we generate a great amount of messages in a context of very high load and a very sensitive app we can't allow to be stoping messages just for any problem with Elastic because when Elastic comes to live then all stoped messages are sent and then Elastic gets collapsed, and then we stop more messages again.
Limiting the amount of disk space for the buffer file doesn't solve this problem and also it can introduce a new problem (maybe the shipping to Elastic works fine and we reach the buffer file limit and then we lose messages when there is no problem at all).
As summary, I love the way the durable mode works, but for some very sensitive apps I prefer to lose messages rather than affecting my app and my Elastic (for the big amount of messages it generates).

It should work for me also to have a max value of pending messages to be shipped, so there would be a margin of movement and not allways losing messages when the shipping to Elastic fails, but it is more complex to develop.

Thanks a lot.

**Comment by freeranger** [comment]
@jose3m why not simply turn off durable mode then? You dont mind losing messages; if elastic is down you will lose messages; problem solved?

**Comment by jose3m** [comment]
@freeranger The durable mode has some features I want to use still: it doesn't consume RAM as it buffes on disk, you can set it to send messages waiting x seconds and not inmediatelly, it sends messages on another task or thread (i don't remember now), etc..

**Comment by jose3m** [comment]
Hi.

Is it possible a PR? Or do you still think that this behaviour is not necessary?

Thanks.

**Comment by mivano** [comment]
The queueSizeLimit has been added to the 5.5 release.

**Comment by jose3m** [comment]
Hi.

For what I can read on the source font the QueueSizeLimit doesn't work for the durable mode. Correct?

**Comment by mivano** [comment]
Correct. No changes yet to the durable mode. I rather work away the durable option completely and let it be handled higher in the stack (https://github.com/serilog/serilog-sinks-seq/issues/51#issuecomment-338511037). But that is more effort to create.

**Comment by mivano** [comment]
Closing for now
