### ISSUE TITLE
Question: Buffer files

### ISSUE THREAD

**Issue by kimbell** [serilog/serilog-sinks-elasticsearch#120]
I've set up Serilog to log against elastic search and trying to figure out how the buffer files work. Default they are set to around 5MB. When they reach the max size, things seems to stop working. 

Should the size of these files be enough to cover all logging for one day (assuming daily rollover)? 
As long as you can contact Elastic search, should these files be used?

**Comment by frg** [comment]
+1 I've got the same issue

**Comment by alaniemieckota** [comment]
I have got the same issue, when buffer file reaches bufferFileSizeLimitBytes then the buffer file stops growing and elastic index stops indexing documents.

**Comment by kimbell** [comment]
I think I have figured out why it behaves this way. Internally the elastic search sink uses the rolling file sink; this doesn't know that events will be shipped off to some other location. 

On a different note, I've come to see that it's not a bad idea to keep the events on file as well as in elastic search. That way it's easy to re-index them should the need arise. I attended a presentation on ELK, and people have deleted tons of data accidentally in production.

**Comment by alaniemieckota** [comment]
In my opinion it is a really bad idea to keep events on files when I want to use Elastic. If I wan to have logs in files I am using [Rolling File Sink](https://github.com/serilog/serilog-sinks-rollingfile). I agree that this is a good source for re-indexing, but if someone have problems with data lose, a "feature" of broken buffer file should not be the solution.

**Comment by mivano** [comment]
As it is pretty easy to add multiple sinks to serilog, you can just as well write to a file sink. The durable buffer is there to handle connectivity issues with ES. So when the connection drops for some reason. There are more ways to do this, like pushing it to a file sink and let logstash handle the piping to ES (using something like a queue in between).
