### ISSUE TITLE
ElasticSearch Sink not keeping up

### ISSUE THREAD

**Issue by frg** [serilog/serilog-sinks-elasticsearch#123]
Hi, I'm trying to tune the configuration for large rates of log events but I can't seem to find a sweet spot were this sink would keep up. My current rate is at ~1.8k / 30 seconds (This might actually be the problem but I've already trimmed down and ideally I wouldn't have to trim the verbosity further).

After looking into the code I can see that only 1 instance can ship a single batch at a time.

https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchLogShipper.cs#L141

I understand why the bookmark was implemented like this but it seems like that's becoming a bottleneck.

My current config is the following
```
{...
              "bufferBaseFilename": "./Logs/elasticbuffer",

              // The maximum number of events to post in a single batch.
              // https://www.elastic.co/guide/en/elasticsearch/guide/current/bulk.html#_how_big_is_too_big
              // Assuming every event is ~400 bytes, 25000 events would equal ~10MB
              "batchPostingLimit": 25000, // Passed to PeriodicBatchingSink
              
              // The time (in seconds) to wait between checking for event batches.
              "period": 1, // Passed to PeriodicBatchingSink
              
              // The interval (in milliseconds) between checking the buffer files.
              "bufferLogShippingInterval": 100,
              
              "bufferFileSizeLimitBytes": 2147483648 // 2GB, Passed to RollingFile Sink
... }
```

Now obviously there are other bottlenecks that might be at play but can someone recommend the next step in improving my config / setup?

**Comment by nblumhardt** [comment]
One option, not sure how palatable, is to just use non-durable shipping. It should easily sustain this rate, though of course there are trade-offs.

A (possibly hacky) option is to use _Serilog.Sinks.Map_ to distribute events over several instances of the sink, using different buffer files. Writes to the buffer file are still going to be a problem at some point, but you might improve throughput a bit.

```
    // Spread events over five sinks/buffers
    .WriteTo.Map(le => le.Timestamp.Millisecond % 5,
        (ms, wt) => wt.Elasticsearch(..., "/Logs/elasticbuffer-{ms}"))
```

;-)

**Comment by frg** [comment]
I've thought about removing durability all together as it will at least fix the keeping up issue, but I'me going to test out Map first.

Will let you know how it goes, thanks @nblumhardt :)

**Comment by frg** [comment]
Map does not have good support with Serilog.Configuration thus I won't work for me. I'm going to switch off durable mode until I find a better way. The possibility of losing some logs is better than having none.

Thanks @nblumhardt for your help.
