### ISSUE TITLE
Using a client certificate

### ISSUE THREAD

**Issue by smiffy1989** [serilog/serilog-sinks-elasticsearch#126]
Apologies up front, this is more of a question than it is an issue (there may be an issue?!) and it may also be best to ask against elasticsearch-net rather than here!

I'm trying to use a client certificate by doing this:
```
ElasticsearchSinkOptions options = new ElasticsearchSinkOptions(new Uri("https://XXXX.com"))
{
       IndexFormat = "seri-log-{0:yyyy.MM}",
       ModifyConnectionSettings = connectionConfiguration => connectionConfiguration.ClientCertificate(myX509))
};
```

But doing that I get:

> Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.ElasticsearchSink: Elasticsearch.Net.UnexpectedElasticsearchClientException: The ClientCertificateOptions property must be set to 'Manual' to use this property. ---> System.InvalidOperationException: The ClientCertificateOptions property must be set to 'Manual' to use this property.

The only way I've found to get it to work is to do this:
```
       class Foo : HttpConnection
       {
              protected override HttpClientHandler CreateHttpClientHandler(RequestData requestData)
              {
               ...
                           handler.ClientCertificateOptions = ClientCertificateOption.**Manual**;
               ...
              }
        }

      ElasticsearchSinkOptions options = new ElasticsearchSinkOptions(new Uri("https://XXXX.com"))
      {
             Connection = new Foo(),
             ModifyConnectionSettings = connectionConfiguration => connectionConfiguration.ClientCertificate(myX509))
      };

```

Is there a better way of doing this where I don't have to override the whole of CreateHttpClientHandler?

Probably worth mentioning that I'm using a load balancer to do SSL decryption and forwarding on to elastic.

**Comment by mivano** [comment]
Interesting problem. Never tried it with certificates but all communication goes via the elasticsearch.net library. I would suggest checking there what the best pattern is to use.

**Comment by mivano** [comment]
Found a solution you can share?

**Comment by makhdumi** [comment]
This was an issue in the Elasticsearch .NET driver, specific to .NET Core, and the fix was merged in a few days ago here: https://github.com/elastic/elasticsearch-net/pull/3242
