### ISSUE TITLE
Lost events on CloseAndFlush with durable sink

### ISSUE THREAD

**Issue by rumatavz** [serilog/serilog-sinks-elasticsearch#130]
I'm using package 5.3.0 net461

Bookmark contains one record:
18704:::c:\temp\SerilogBuffer\SerilogBuffer-20171114.json

There are two files 
* SerilogBuffer-20171115.json
* SerilogBuffer-20171114.json

When I call CloseAndFlush no messages from SerilogBuffer-20171115.json pushed to elastic.

There is a problem in ElasticsearchLogShipper.OnTick on line  while (count == _batchPostingLimit);
It is correct only if I have one file.
For example I need to sync 45 events from SerilogBuffer-20171114 and 10 from SerilogBuffer-20171115.
For the first file count == 45 and loop ends. It is not very bad during app run, but on dispose 10 messages from second file are not sync.

You can easily reproduce the problem using my buffer:
[buffer.zip](https://github.com/serilog/serilog-sinks-elasticsearch/files/1474702/buffer.zip)
Consider using BufferLogShippingInterval = TimeSpan.FromHours(1) during debugging.

**Comment by nblumhardt** [comment]
@rumatavz I think this is by design - if you leave the app running, or when you start the app back up, it should ship the rest of the events. The sink doesn't completely flush the disk buffer on shut-down.

**Comment by rumatavz** [comment]
Imagine you are using Serilog+Elastic+Watcher in prod. And after a power fail(or smth like that) your app can't start. It tries to start and immediately fails. And this situation longs for hours. You are waiting for a mail or SMS from watcher but sink just don't send error messages to elastic.

If it's by design so design don't fit prod systems.

**Comment by nblumhardt** [comment]
Thanks for the feedback! Great scenario, seems like something we could improve just by forcing _at least one_ batch of events to be sent with each flush...

(The problem with shipping the whole file on shut-down is similarly nasty - imagine that your Elastic server changed addresses or ports, or was shut down for a while. The file could be _big_, so flushing the whole thing on shut-down might push shut-down time past acceptable levels.)

**Comment by AceHack** [comment]
@nblumhardt also in docker, the file is gone on restart.

**Comment by mivano** [comment]
Old issue, cleaning up
