### ISSUE TITLE
Wiki documentation does not match actual code and is not up-to-date

### ISSUE THREAD

**Issue by kbatman37** [serilog/serilog-sinks-elasticsearch#131]
1. The `access logs` page on the wiki is 'tbd' and has been for some time
1. The `configure` page mentions that 
    - the `Period` is in seconds, it is actually a `TimeSpan` object
    - the `ConnectionTimeout` is in miliseconds, it is actually a `TimeSpan` object and the default value listed does not match the default value listed in the comment / intelisense

**Comment by addamichal** [comment]
Also, Appsettings minimumLogEventLevel should be restrictedToMinimumLevel

**Comment by mivano** [comment]
Thanks. Updated the page (and removed the empty one)
