### ISSUE TITLE
Using IConnectionPool implementation that supports Sniffing leads to infinite loop of discovery

### ISSUE THREAD

**Issue by samusaran** [serilog/serilog-sinks-elasticsearch#133]
## Bug found on
- .Net Core 2.0 (ASP NET Core 2.0 self-host service)
- ElasticSearch Sink v5.5.0
- ElasticSearch Cluster v5.6.4

## Current behavior
Using any IConnectionPool implementation that supports Sniffing, leads to an infinite loop of API calls to the `/_nodes` endpoint of the cluster.

My code in program.cs
```csharp
        private static IConnectionPool GetIConnectionPool(IConfiguration configuration)
        {
            Func<Node, float> nodeScorer = n =>
            {
                if (n.IngestEnabled && !n.HoldsData && !n.MasterEligible) return 1f; // Dedicated Ingest
                if (n.IngestEnabled && n.HoldsData && n.MasterEligible) return 0.5f; // MDI Node
                return 0f; // Other
            };

            IEnumerable<Uri> uris = configuration.GetSection("elasticsearch:nodeUris").Get<string[]>().Select(x => new Uri(x));
            return new StickySniffingConnectionPool(uris, nodeScorer);
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder()
                .ConfigureAppConfiguration((builderContext, config) =>
                {
                    config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
                })
                .UseKestrel(options =>
                {
                    options.Listen(IPAddress.Any, 80);
                })
                .UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration
                     .WriteTo.Elasticsearch(new Serilog.Sinks.Elasticsearch.ElasticsearchSinkOptions(GetIConnectionPool(hostingContext.Configuration))
                     {
                         IndexFormat = "sistemigateway",
                         TypeName = "log",
                         BatchPostingLimit = 1000,
                         MinimumLogEventLevel = LogEventLevel.Information,
                         NumberOfShards = 1,
                         NumberOfReplicas = 2,
                         ModifyConnectionSettings = settings => settings
                            .BasicAuthentication(hostingContext.Configuration["elasticsearch:username"], hostingContext.Configuration["elasticsearch:password"])
                            .DisableAutomaticProxyDetection()
                     })
                     .WriteTo.Console()
                     .Filter.ByIncludingOnly(le => le
                        .Level > LogEventLevel.Information || le
                        .Properties["SourceContext"].ToString().Contains("SharpReverseProxy"))
                )
                .UseStartup<Startup>()
                .Build();
    }
```

Fiddler trace:
![immagine](https://user-images.githubusercontent.com/290743/34037789-592f1012-e18a-11e7-9886-2bdc736f1787.png)

## Expected behaviour

I'm expecting an initial discovery, followed by `_bulk`s of my logged events.

## How to reproduce:

Try my code, with `StickySniffingConnectionPool` or `SniffingConnectionPool`.

**Comment by Mpdreamz** [comment]
Are you using Elasticsearch 6.1?

**Comment by samusaran** [comment]
I'm using Elasticsearch 5.6.4. I'll add it to the thread.

**Comment by mivano** [comment]
Found a solution yet? Is this related to the sink or more to the underlying Elasticseach.net library?

**Comment by samusaran** [comment]
Actually I still have the issue, with both 5.6.0 and 6.1.0 Sink (Elasticsearch 5.6.4).

The issue is unchanged. Using StaticConnectionPool, the sink works as expected, while using a StickySniffingConnectionPool, the Sink just keep discovering nodes and not logging anything.

I thought it was our corporate proxy messing with how the discovery works (we had this problem before, since the sniffing does not work with FQND but falls back to IPs) but even setting `.DisableAutomaticProxyDetection()` does not change the behaviour.

**Comment by mivano** [comment]
Sorry, I m not using this feature, but the whole connectionpool is handled by the underlying Elasticsearch.net library. The sink does not do anything special with this. Might be worthwhile to check over here: https://github.com/elastic/elasticsearch-net

**Comment by samusaran** [comment]
I should have been more specific. We are actually using the same connection pool successfully on our web applications but it fails when we use it with the Sink.

### Working configuration that we use to communicate to elasticsearch on ASP.NET
```csharp
Func<Node, float> nodeScorer = n =>
{
    if (n.IngestEnabled && !n.HoldsData && !n.MasterEligible) return 1f; // Dedicated Ingest
    if (n.IngestEnabled && n.HoldsData && n.MasterEligible) return 0.5f; // MDI Node
    return 0f; // Other
};

var uris = System.Configuration.ConfigurationManager.AppSettings["ADR_ELASTIC_REP"].Split(';');
var nodes = uris.Select(u => new Uri(u));
var pool = new StickySniffingConnectionPool(nodes, nodeScorer);
```

### Non-working Serilog Sink configuration on ASP.NET Core
```csharp
IEnumerable<Uri> uris = configuration.GetSection("elasticsearch:nodeUris").Get<string[]>().Select(x => new Uri(x));

Func<Node, float> nodeScorer = n =>
{
    if (n.IngestEnabled && !n.HoldsData && !n.MasterEligible) return 1f; // Dedicated Ingest
    if (n.IngestEnabled && n.HoldsData && n.MasterEligible) return 0.5f; // MDI Node
    return 0f; // Other
};
return new StickySniffingConnectionPool(uris, nodeScorer);
```

The first can communicate with elastic with no problem, while the second one, used with the Sink, it just autodiscover the nodes repeately, and never logs anything.
We have a cluster structured in a way that we have read-dedicated nodes and write-dedicated nodes. In an infrastructure were basically every web application we have just logs to elasticsearch, using a StaticConnectionPool pointing to write-only nodes it's just dangerous, because I have to tradeoff load balancing with availability (is it ok to lose all writes if ingest nodes goes down because I configured the app with no fallback node?)

I will take a look at how the IConnectionPool is actually used in the sink, because I still haven't figured out how to work around this issue using configurations.

**Comment by mivano** [comment]
That is indeed strange. @Mpdreamz any clue about this?

**Comment by mivano** [comment]
I have no more information on this. I hope it was resolved, closing the issue for now.
