### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by bityoda** [serilog/serilog-sinks-elasticsearch#137]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ X] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
<PackageReference Include="Serilog.Sinks.ElasticSearch" Version="5.5.0" /> 

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
Hello,
we have a basic Microservice Setup running in AWS using Serilog for logging to an ElasticSearch Microservice.

With a mostly basic setup, listed below, we have a high cpu usage, related to the "Periodicbatching" Time Ticker approach. As far as i could see in debugger. One CPU Core is mostly completely in use, even if the server has no requests.

Interesting, if i increase the period property to 10 seconds, the effect is gone. 

var elasticSearchSinkOptions = new ElasticsearchSinkOptions(new Uri(serviceDiscovery.ElasticSearchServerUrl))
            {
                IndexFormat = "mslogindex-{0:yyyy.MM}", // references to Index Pattern MicroServiceLogIndex-* in Kibana
                TemplateName = "MicroServiceLoggingTemplate",
                AutoRegisterTemplate = true,
                TypeName = "LogEventType",
                BatchPostingLimit = 50,
                Period = new TimeSpan(2000),
                InlineFields = true,
                MinimumLogEventLevel = LogEventLevel.Verbose
            };

**Please describe the expected behavior?**

Independent from the period time setting or available capacity of the server, the base CPU load should not be remarkable, only for logging.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

**Comment by mivano** [comment]
Strange issue. Did you try to enable the selflog of serilog and see if it is throwing exceptions somewhere?

**Comment by mivano** [comment]
Any clues yet? See anything in the logs?

**Comment by mniak** [comment]
Wow, I have the exact same issue but with the Azure Event Hub sink. I'll try increasing the period and will post if it made any difference.
