### ISSUE TITLE
No `LoggingLevelSwitch` option in the extension method

### ISSUE THREAD

**Issue by piaste** [serilog/serilog-sinks-elasticsearch#138]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**Please describe the current behavior?**

The `LoggerSinkConfiguration.Elasticsearch()` method allows you to specify a minimum logging level, but does not have an option to pass in a `LoggingLevelSwitch` object through which the minimum logging level can be changed at runtime.

Adding this object would allow a user to set a different log level for the ElasticSearch sink compared to any other sinks in use.

Note that the object can simply be passed immediately to the `LoggerSinkConfiguration.Sink()` method and does not require any actual implementation.

**Please describe the expected behavior?**

There should be a `LoggingLevelSwitch` property in the `ElasticsearchSinkOptions` class to enable use of this feature. Many Serilog sinks (including Console and File) have this option.

I will shortly submit a PR to add this property.

**Comment by mivano** [comment]
Merged and released.
