### ISSUE TITLE
Configure ExceptionAsObjectJsonFormatter via AppSettings

### ISSUE THREAD

**Issue by iss0** [serilog/serilog-sinks-elasticsearch#143]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
latest

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [x] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
I am not able to configure the ExceptionAsObjectJsonFormatter  via App.Config or Web.Config.

**Please describe the expected behavior?**
I would like to configure it that way. :-)

**Comment by mivano** [comment]
Old issue, cleaning up
