### ISSUE TITLE
Question: Handling self signed certificates

### ISSUE THREAD

**Issue by kimbell** [serilog/serilog-sinks-elasticsearch#144]
I'm running on ASP.NET Core 2.0, setting up logging in program.cs and reading configuration from appsettings.json. Currently I've been using http, but we want to move over to https and self signed certificates. 

Is there a way that I can ignore SSL validation errors? 

I've been digging around and can see that the Elasticsearch.Net sets up a handler for ServerCertificateCustomValidationCallback, but I cannot see if that is made available in some way through the Serilog sink. 

The ElasticSearchSinkOptions has a Connection property that looks promising, but I haven't been able to get hold of a reference to the options object when using ReadFrom.Configuration(hostBuilder.Configuration)    

  ```
 <PackageReference Include="Serilog.AspNetCore" Version="2.1.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="2.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.Elasticsearch" Version="5.5.0" />
```

In Program.cs:

```
.ConfigureLogging((hostBuilder, configureLogging) =>
                {
                    IHostingEnvironment environment = hostBuilder.HostingEnvironment;

                    if (environment.IsUnitTest())
                    {
                        return;
                    }

                    var configuration = new LoggerConfiguration();

                    configuration
                         .ReadFrom.Configuration(hostBuilder.Configuration)                          
                         .WriteTo.Console();                    
                    configureLogging.AddSerilog(configuration.CreateLogger());
                })
```

**Comment by mivano** [comment]
Not directly sure, but you can access the ModifyConnectionSettings on the options of the sink. You need to do an explicit Write like this:

```csharp
    Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://elastic:changeme@localhost:9200")) // for the docker-compose implementation
                {
                    ModifyConnectionSettings = configuration =>    configuration.ServerCertificateValidationCallback(
                        (o, certificate, arg3, arg4) => { return true; }),
                 })
                .CreateLogger();
```     

See https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/working-with-certificates.html for details on the options.

**Comment by kimbell** [comment]
That approach would mean having to build your own configuration objects to pass the various values to the code. I really like the `configuration.ReadFrom.Configuration(hostBuilder.Configuration)` that allows me to configure things in appsettings.json

Ideally it should be a way of getting access to ElasticSearchSinkOptions using this configuration method. That would allow code to augment properties set by a configuration file.

**Comment by mivano** [comment]
I could not agree more. Ideally, everything should be configurable using the configuration readers. But these kinds of things are very tricky to make generic as it uses the all-purpose serilog configuration tooling. Certainly with nested properties and other types (like different serializers), it is harder to make this easy to config.

So for now; yes you will need to init this sink by code and pass in your own config options.
