### ISSUE TITLE
Durability feature depends on RollingFile sink which is now a part of the File sink 

### ISSUE THREAD

**Issue by tafs7** [serilog/serilog-sinks-elasticsearch#146]
Are there any plans to change the dependency away from the RollingFile sink and towards the File sink version 4?

According to the blog post by @nblumhardt at https://nblumhardt.com/2017/10/serilog-file-logging/ :
>An early design decision — to split the primitive Serilog.Sinks.File sink from the Serilog.Sinks.RollingFile sink built on top of it — stood in the way of implementing some of the most-requested features, rolling on file size being the most obvious example. So, we’re changing direction and **effectively merging these two packages into a single codebase with Serilog.Sinks.File version 4.0.0.**

**Comment by mivano** [comment]
No concrete plans, but it can certainly be improved. See also https://github.com/serilog/serilog-sinks-seq/issues/51#issuecomment-278466974
Care for some PR?

**Comment by mivano** [comment]
Old issue, cleaning up. PR has been merged.
