### ISSUE TITLE
WriteTo.Elasticsearch blows up not finding a method in Elasticsearch.Net.ConnectionConfiguration

### ISSUE THREAD

**Issue by afederici75** [serilog/serilog-sinks-elasticsearch#147]
Hi,
  This is my first time trying this sink. Any help is much appreciated!

- [X] Bug

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
5.7 which depends on Elasticsearch.Net 6.0.0-rc1 which is what I use

**What is the target framework and operating system? 
- [X] netCore 2.0

**Please describe the current behavior?**
I just downloaded the ES sink and tried in my solution, but when I call .WriteTo.ElasticSearch(options) I get the following error:

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void Elasticsearch.Net.ConnectionConfiguration..ctor(Elasticsearch.Net.IConnectionPool, Elasticsearch.Net.IConnection, System.Func`2<Elasticsearch.Net.ConnectionConfiguration,Elasticsearch.Net.IElasticsearchSerializer>)'.
  Source=Serilog.Sinks.Elasticsearch
  StackTrace:
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState..ctor(ElasticsearchSinkOptions options)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.Create(ElasticsearchSinkOptions options)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink..ctor(ElasticsearchSinkOptions options)
   at Serilog.LoggerConfigurationElasticsearchExtensions.Elasticsearch(LoggerSinkConfiguration loggerSinkConfiguration, ElasticsearchSinkOptions options)

**Please describe the expected behavior?**
For it to work? :)

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

var uris = startupSettings.Elasticsearch.Addresses.Select(x => new Uri(x)).ToList();
var sinkOptions = new Serilog.Sinks.Elasticsearch.ElasticsearchSinkOptions(uris)
{
  AutoRegisterTemplate = true,
  IndexFormat = $"{startupSettings.SystemName.Value.ToLower()}-{0:yyyy.MM}",                    
};
cfg.WriteTo.Elasticsearch(sinkOptions);

**Comment by mivano** [comment]
Interesting. The current referenced Elasticsearch.net version is 5.5. I have not tested with 6.0 yet. Looks like some breaking changes.

**Comment by piaste** [comment]
Confirm a breaking change. Today I tried updating from 5.6 to 6.0 and it broke with the same error message.

**Comment by mivano** [comment]
Old issue, cleaning up
