### ISSUE TITLE
Configure more ElasticsearchSinkOptions through AppSettings

### ISSUE THREAD

**Issue by letargis** [serilog/serilog-sinks-elasticsearch#149]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [X] New Feature

**Please describe the current behavior?**
Only limited subset of ElasticsearchSinkOptions properties allowed to configure through AppSettings.

**Please describe the expected behavior?**
I understand that it is hard to configure properties of Func<>, but I propose to extend number of simple parameters. For my current task I need to manage numberOfShards and numberOfReplicas properties from configuration, so I propose to add to appSettings following properties:

- autoRegisterTemplate
- autoRegisterTemplateVersion
- overwriteTemplate
- numberOfShards
- numberOfReplicas

**Comment by mivano** [comment]
See my feedback at the PR.
