### ISSUE TITLE
Elastic sink throws MissingMethodException re: PeriodicBatchingSink

### ISSUE THREAD

**Issue by adamheinmiller** [serilog/serilog-sinks-elasticsearch#151]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**

Serilog.Sinks.Elasticsearch 5.7.0
Serilog.Sinks.PeriodicBatchingSink 2.1.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ ] netCore 2.0
- [ ] netCore 1.0
- [ x] 4.7
- [ x] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**

Using Elastic sink version 5.7 with Periodic batching sink version 2.1.1 causes the Elastic sink to throw a MissingMethodException during sink configuration:

Method not found: 'Void Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink..ctor(Int32, System.TimeSpan, Int32)'.

   at Serilog.Sinks.Elasticsearch.ElasticsearchSink..ctor(ElasticsearchSinkOptions options)
   at Serilog.LoggerConfigurationElasticsearchExtensions.Elasticsearch(LoggerSinkConfiguration loggerSinkConfiguration, ElasticsearchSinkOptions options)
   at ***********

Downgrading to Elastic sink version 5.5 and periodic batch version 2.1.0 resolves the error.

**Please describe the expected behavior?**

It should not blow up.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

**Comment by mivano** [comment]
The latest package has some updated libraries. Can you try out https://www.nuget.org/packages/Serilog.Sinks.ElasticSearch/6.1.0-unstable0013 ?

**Comment by adamheinmiller** [comment]
Apologies for the delay.  We were able to identify and resolve the issue.  Periodic Batching 2.1.0 had been errantly installed in an unrelated class library and was not updated to 2.1.1.  The resulting version mismatch caused the issue.  Removing the old version fixed the error.
