### ISSUE TITLE
How to log custom fields to ES index

### ISSUE THREAD

**Issue by justintoth** [serilog/serilog-sinks-elasticsearch#156]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [X] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
5.7.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
It logs the default fields to the ES index.

**Please describe the expected behavior?**
I'm wondering how I go about adding custom fields to the ES index? I need to log not just date / message / etc..., I also need to log custom fields such as a user's email address.

**Comment by justintoth** [comment]
Never mind, it looks like adding additional fields in ES works the same way as with other sinks that leverage ILogger:

```
using (_logger.BeginScope(new Dictionary<string, object>{
                ["UserName"] = context.HttpContext.User.Identity.Name,
                ["RequestJson"] = requestJson, 
                ["Host"] = context.HttpContext.Request.Host.ToString(),
                ["Method"] = context.HttpContext.Request.Method,
                ["Path"] = context.HttpContext.Request.Path,
                ["QueryString"] = context.HttpContext.Request.QueryString.ToString()
            }))
            {
                _logger.LogError(context.Exception, context.Exception.Message);
            }
```

**Comment by mivano** [comment]
Correct. It will pick up any fields you log. Have a look at enrichers to see how you can add usernames etc by default.

**Comment by BoasE** [comment]
btw is this style meant to be thread safe? @mivano

**Comment by mivano** [comment]
I m not sure. Best to ask in the main serilog tracker.
