### ISSUE TITLE
ElasticsearchJsonFormatter should set render message to true by default

### ISSUE THREAD

**Issue by klettier** [serilog/serilog-sinks-elasticsearch#158]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
* All

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- All

**Please describe the current behavior?**

When I'm calling ```WriteTo.Elasticsearch``` without providing any ```CustomFormatter``` in ```ElasticsearchSinkOptions``` it will create a formatter with property ```renderMessage``` set to ```true``` see [here](https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs#L82).

If I'm providing my own instance of ```ElasticsearchJsonFormatter``` I have to be aware of that behavior to avoid losing my ```message``` property because the default behavior is to set ```renderMessage``` to false see [here](https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchJsonFormatter.cs#L52)

**Please describe the expected behavior?**

I think we should be consistent here and set ```renderMessage``` to true by default in the constructor of ```ElasticsearchJsonFormatter```

**Comment by mivano** [comment]
Merged
