### ISSUE TITLE
Add ability to avoid rendering MessageTemplate

### ISSUE THREAD

**Issue by klettier** [serilog/serilog-sinks-elasticsearch#159]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

It would be great to be able to disable the rendering of ```MessageTemplate``` in ```ElasticsearchJsonFormatter``` the same way we can avoid to render the message see [here](https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchJsonFormatter.cs#L52)

**Comment by mivano** [comment]
Merged
