### ISSUE TITLE
Allow to specify connection via appsettings

### ISSUE THREAD

**Issue by reedz** [serilog/serilog-sinks-elasticsearch#161]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [X] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
6.3.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [X] netCore 1.0
- [X] 4.7
- [X] 4.6.x
- [X] 4.5.x

**Please describe the current behavior?**
Not possible to specify "connection" option via app settings.

**Please describe the expected behavior?**
Should be possible to specify "connection" option via app settings (xml or json) since serilog configuration allows to instantiate interface implementations and abstract types if they contain parameter-less constructor.

**Motivation**
Connections to private-owned ES servers in windows environments seldom use windows authentication feature which requires setting default credentials on requests - which is suggested to be performed via IConnection implementation: https://github.com/serilog/serilog-sinks-elasticsearch/issues/75

**Comment by mivano** [comment]
Merged. tx
