### ISSUE TITLE
Sink does not work without external IP

### ISSUE THREAD

**Issue by billHaggerty** [serilog/serilog-sinks-elasticsearch#163]
Possible bug

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
6.3.0

**What is the target framework and operating system?

netCore 2.0 
ubuntu 16.04 LTS google vm in google cloud compute with a squid proxy

**Please describe the current behavior?**
The sink fails to upload any logs to sematext, throws Cannot connect to server exceptions.
 Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.ElasticsearchLogShipper: Elasticsearch.Net.ElasticsearchClientException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server

This only happens on a google ubuntu 16.04 LTS vm that does not have an external IP address, but does have a proxy configured for web traffic. I am calling .DisableAutomaticProxyDetection(false) and set the connection timeout to five mins via the ModifyConnectionSettings property, so it should detect the proxy right away and work right?

**Comment by mivano** [comment]
Old issue, cleaning up
