### ISSUE TITLE
key="serilog:using" required for appSettings conf.

### ISSUE THREAD

**Issue by harleydk** [serilog/serilog-sinks-elasticsearch#165]
I had in mind to do a pull request, but am unable to. Likely because of some two-factor authentication issue on my side. Anyways,

I've found the "&lt;add key="serilog:using" value="Serilog.Sinks.Elasticsearch"/&gt;" is in fact required for making the .ReadFrom.AppSettings() work as intended. The readme.md doesn't reflect this. I humbly suggest replacing the current paragraph "With the appSettings configuration[...]" with the below:

---suggested paragraph start---

With the appSettings configuration the `nodeUris` property is required. Multiple nodes can be specified using `,` or `;` to seperate them. Also required is the '&lt;add key="serilog:using" value="Serilog.Sinks.Elasticsearch"/&gt;' setting. All other properties are optional. If you do not specify an indexFormat-setting, a generic index such as 'logstash-[current_date]' will be created automatically. 

---suggested  paragraph end---

Thank you for your consideration.

**Comment by mivano** [comment]
Thanks, I added this to the readme.
