### ISSUE TITLE
Custom templateName is not visible in Kibana

### ISSUE THREAD

**Issue by siberianguy** [serilog/serilog-sinks-elasticsearch#167]
I'm trying to use Elastic Search + Kibana for the first time. I've specified a simple configuration and everything worked but then I tried to customise indexFormat and templateName (I want to use different storages for development and production logs but I don't see a customised index in a "create index pattern" window (I still see only the default one: logstash-2018.04.19)

```
  "Serilog": {
    "WriteTo": [{
      "Name": "Elasticsearch",
      "Args": {
        "nodeUris": "https://xxx.amazonaws.com",
        "indexFormat": "templateName",
        "templateName": "templateName"
      }
    }]
  }
```

Am I missing something?

**Comment by mivano** [comment]
Can you enable the selflog of serilog and see if you get any errors?

**Comment by siberianguy** [comment]
@mivano, thanks a lot! Just starting working with Serilog, had no idea about this feature. It turned out I was using capital letters in indexformat
