### ISSUE TITLE
Named parameter configuration doesn't work anymore

### ISSUE THREAD

**Issue by sunib** [serilog/serilog-sinks-elasticsearch#174]
Just updated my package from
```<package id="Serilog.Sinks.Elasticsearch" version="6.3.0" targetFramework="net461" />```
To
```<package id="Serilog.Sinks.Elasticsearch" version="6.5.0" targetFramework="net461" />```

Until the update I configured the sink in code like this:
```
.WriteTo.Elasticsearch(
                            nodeUris: logElasticsearchHosts,
                            indexFormat: logElasticsearchIndexFormat, 
                            restrictedToMinimumLevel: Serilog.Events.LogEventLevel.Debug,
                            bufferBaseFilename: filenameElasticBuffer)
```
It's using a big ctor, and thanks to the named parameters I only need to insert the values that I want to be changed. But now in v6.5.0 I get an ambiguous error. Thats because multiple big ctor's are available.

So now I need to write:
```
.WriteTo.Elasticsearch(logElasticsearchHosts,
                            logElasticsearchIndexFormat, 
                            null, 
                            "logevent", 
                            50, 
                            2, 
                            false,
                            Serilog.Events.LogEventLevel.Debug, 
                            filenameElasticBuffer,      
                            null, 
                            5000, 
                            null, 
                            null, 
                            5, 
                            Serilog.Sinks.Elasticsearch.EmitEventFailureHandling.WriteToSelfLog, 
                            100000, 
                            null, 
                            false, 
                            Serilog.Sinks.Elasticsearch.AutoRegisterTemplateVersion.ESv2, 
                            false, 
                            Serilog.Sinks.Elasticsearch.RegisterTemplateRecovery.IndexAnyway, 
                            null, 
                            null, 
                            null)
```

I do need the multiple hosts string option, which isn't available in the `ElasticsearchSinkOptions` object.

Perhaps it's an idear to create an extra ctor in the ElasticsearchSinkOptions that would take a string with multiple hosts? Shall I create a pull request?

Or perhaps it's possible to remove one of the big ctor's?

**Comment by mivano** [comment]
I think cleaning up the other ctors might be better although it can be a breaking change. More and more people want to use the appsettings to configure the sink and a lot of options are now available. Care for a PR?

**Comment by mivano** [comment]
I believe some changes have been done here. Old issue, cleaning up. Still facing this issue, feel free to reopen.
