### ISSUE TITLE
Introduce configuration options for renderMessage and renderTemplate formatter paramters

### ISSUE THREAD

**Issue by flavio1110** [serilog/serilog-sinks-elasticsearch#178]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [X] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
6.5.0+

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
There are parameters for control if the message and its template will be rendered or not in the the constructor of _ElasticsearchJsonFormatter_. However if we want set that we can't use the configuration file because there are no such properties in _ElasticsearchSinkOptions_, therefore we need to configure it in code.

**Please describe the expected behavior?**
I would like to set the configuration file like shown below and those values are set in the default formatter.:

`    "WriteTo": [{ 
        "Name": "Elasticsearch", 
        "Args": { 
          "nodeUris": "http://localhost:9200;",
          "minimumLogEventLevel": "Debug",
          "autoRegisterTemplate": true,
          "autoRegisterTemplateVersion" : "ESv6",
          "inlineFields" : true,
          "bufferBaseFilename" : "./logs/buffer",
          "renderMessage" : false,
          "renderMessageTemplate" :  false
        }       
    }],`

There is the renderMessage in _ExceptionAsObjectJsonFormatter_ too, but it can't be defined via configuration as well the default one.

I'll be happy in work in this modification if it gets approved.

All the best,

**Comment by mivano** [comment]
Old issue, cleaning up. Still facing this issue, feel free to reopen.

**Comment by esskar** [comment]
The issue still remains. The options are not available from outside, or am I missing something?
