### ISSUE TITLE
Port buffer file improvements from Serilog.Sinks.Seq

### ISSUE THREAD

**Issue by nvivo** [serilog/serilog-sinks-elasticsearch#179]
Currently, this sink is using RollingFile as buffer, and it has some serious limitations, that whether the buffer file grows without limits, or the file is size-limited and the sink stops working after that. This is making the durable mode unusable with this sink.

I'm currently using the sink without durable mode, but this is a problem as some events may go missing for various reasons. The Seq sink had the same issues, and they [were fixed on version 4.0](https://github.com/serilog/serilog-sinks-seq/releases/tag/v4.0.0). It would be great if these changes, that is https://github.com/serilog/serilog-sinks-seq/pull/92 and https://github.com/serilog/serilog-sinks-seq/pull/99 would be ported to this sink.

**Comment by nvivo** [comment]
Is it possible to pay to get this implemented? Is anyone interested in resolving this?

**Comment by mivano** [comment]
Would love to have a better/improved version of the buffer, unfortunately too little time to implement. IMHO it would also be nice if this was a more generic Serilog buffer which would pick up events when the configured sink was unable to work.

**Comment by nvivo** [comment]
I currently have this sink and the seq sink logging the same events. For some reason, I have lots of missing events in elastic search that are not logged nor reported in the failure sink/self log. I enabled the selflog, and eventually I get a few failures, but that is probably 1% of what is missing on elastic search.

I'm betting the lack of durable mode is the problem, but that's just a guess. I'll try to debug this at some point.

**Comment by mivano** [comment]
Old issue, cleaning up. There have been some improvement. Still facing this issue, feel free to reopen.
