### ISSUE TITLE
Cannot provide ElasticsearchSinkOptions in code and in configuration

### ISSUE THREAD

**Issue by alastairs** [serilog/serilog-sinks-elasticsearch#180]
**A few questions before you begin:**

**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?**
All versions supporting JSON appsettings configuration up to and including 6.5.0.

**What is the target framework and operating system?**
I assume this behaves the same on all target frameworks.

- [x] netCore 2.0
- [x] netCore 1.0
- [x] 4.7
- [x] 4.6.x
- [x] 4.5.x

**Please describe the current behavior?**
I want to provide default values for `ElasticsearchSinkOptions` in code and override them from the appsettings.json files, environment variables, etc. This appears to be at best tricky to achieve (if not impossible) with the current approach. 

If I create an `ElasticsearchSinkOptions` with my default values for things like `TypeName` and `CustomFormatter`, these take precedence over anything I specify in configuration; indeed, _everything_ specified in configuration appears to be ignored. What I _think_ may be happening in reality is that I'm creating two ElasticSearch sinks, one with the configured options and one with the compiled options. 

Maybe there's a workaround for this that I've not yet discovered?

**Please describe the expected behavior?**
The default values defined in `ElasticsearchSinkOptions` are overridden with the values from configuration.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

1. Create a new project with Serilog, Serilog.Settings.Configuration, and Serilog.Sinks.Elasticsearch
2. Configure Serilog as follows:
```csharp
new LoggerConfiguration()
    .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:9200"))
    {
        // Maybe set some options here, but don't set IndexFormat
    })
    .ReadFrom.Configuration()
    .CreateLogger();
```
3. Configure appsettings as follows:
```json
{
    "Serilog": {
    "Using": [ "Serilog.Sinks.Elasticsearch" ],
    "WriteTo": [{
        "Name": "Elasticsearch",
        "Args": {
          "nodeUris": "https://real.elastic.com:9243",
          "indexFormat": "serilog-{0:yyyy.MM.dd}",
        }
      }],
    }
}
```

**Expected:** Serilog logs to the real Elastic search cluster on the configured URL, writing to the `serilog-*` index pattern.
**Actual:** Serilog logs to two Elastic addresses: the compiled-in localhost address (and fails), and to the default `logstash-*` index on the configured

**Comment by mivano** [comment]
Not everything is indeed possible using the appSettings. There are more and more options available in recent versions though.
