### ISSUE TITLE
Log.Information("{@item}", objectInstance) does not log to Elasticsearch

### ISSUE THREAD

**Issue by reyou** [serilog/serilog-sinks-elasticsearch#182]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**

`Serilog.Sinks.ElasticSearch         {6.5.0}`
`Serilog                             {2.7.2-dev-01010} `       
                
**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x ] netCore 2.1
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Setup**

I tried different Custom Formatters like "`new CompactJsonFormatter()`" instead of "`ExceptionAsObjectJsonFormatter`", but it did not work as well.

```
   Uri node = new Uri("http://localhost:9200");
            ElasticsearchSinkOptions elasticsearchSinkOptions = new ElasticsearchSinkOptions(node)
            {
                AutoRegisterTemplate = true,
                AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv6,
                CustomFormatter = new ExceptionAsObjectJsonFormatter(renderMessage: true),
                IndexFormat = "contosologs-{0:yyyy.MM.dd}"
            };
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Console(new CompactJsonFormatter())
                .WriteTo.Elasticsearch(elasticsearchSinkOptions)
                .CreateLogger();
```

**Please describe the current behavior?**

Example object:
```
  public class CustomTypeForLoggingTest
    {
        public DateTime CreateDate { get; set; }
        public Guid Id { get; set; }
    }

```
`Log.Information("{item}", customTypeForLoggingTest);`

This log shows at Kibana as `MyNameSpace.CustomTypeForLoggingTest` which is not desired. I like object break-up with it's properties.

When I try following one, this does not log at all;
`Log.Information("{@item}", customTypeForLoggingTest);`

**Please describe the expected behavior?**

This should log same way of following setup.
So, it should break-up (serialize) customTypeForLoggingTest object and log it.

```
  Log.Logger = new LoggerConfiguration()
                .WriteTo.Console(new CompactJsonFormatter())
                .CreateLogger();

            User exampleUser = new User { Id = 1, Name = "Adam", Created = DateTime.Now };
            Log.Information("Created {@User} on {Created} {@Thread}", exampleUser, DateTime.Now, Thread.CurrentThread);

            Log.CloseAndFlush();
```

*Debug Message*

> {"type":"mapper_parsing_exception","reason":"failed to parse [fields.User]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:328"}}

**Comment by reyou** [comment]
OK, seems like what is happening is that, we need to be careful while naming the template tokens.

If I send request like below;

![image](https://user-images.githubusercontent.com/6571483/42294694-f850561e-7fb0-11e8-9c61-d9c9495af9b3.png)

Then it creates mapping per token.

![image](https://user-images.githubusercontent.com/6571483/42294704-0f4ba8e6-7fb1-11e8-86df-13689473bbe2.png)

I was thinking it creates mapping per type. But in this case type definition can change over time.

In my error case, I created log with token `User`, but it was a dummy test object, and then tried to create another log with real `User `object, and it fails.

What would be the best practice for these kinds of situations? Maybe we should move our token names in constants, and use that way. Then we may eliminate these kind of collision issues?

**Comment by reyou** [comment]
OK we can close this, since this is not a real bug. More about misuse.

**Comment by Neutrino-Sunset** [comment]
I'm seeing the exact same issue, but I don't understand from the explanation here what the cause of the problem is.

**Comment by mivano** [comment]
The cause is mapping; ES has a type system and the template which can be written to ES contains a mapping table telling the system how to interpret fields. Like how to store and analyze them. When you log an item called A which is an integer, then ES will store inside its index that A as being an integer. When you try to store in the same index the same A but the type is now a string, then ES will throw an exception. Hope this makes sense. Best solution is to carefully think about your naming. There are also hard limits on the number of fields you can store inside a single index.

**Comment by Neutrino-Sunset** [comment]
Thanks, that makes it clearer. I'm surprised there isn't some way to make the method that writes the log entries safer in a way that avoids this issue.

**Comment by mivano** [comment]
I know some people use a different serializer that formats the field names by including the type inside the name. So sending `a` as a string and `a` as an int will end up as two different fields (`string_a` and `int_a`).
Might also not be optimal however, but there is some sort of type system in ES. I m not using the sink myself anymore, so maybe there are better alternatives nowadays.
