### ISSUE TITLE
Update index_patterns when using same template for multiple services

### ISSUE THREAD

**Issue by kimbell** [serilog/serilog-sinks-elasticsearch#186]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
6.5.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
I have multiple ASP.NET Core services sending information to ES. We require some custom configuration for our templates, so I've added the following configuration.
```json
 "Args": {
          "autoRegisterTemplate": true,
          "autoRegisterTemplateVersion": "ESv6",
          "numberOfShards": 5,
          "numberOfReplicas": 0,
          "typeName": "service1",
          "indexFormat": "netcore-service1-{0:yyyy.MM.dd}"
        }
```
When I try to start up a second service, it's not using this template. When inspecting the template, it only has the index pattern for the first service

```json
 "serilog-events-template": {
    "order": 0,
    "index_patterns": [
      "netcore-service1-*"
    ],
```

**Please describe the expected behavior?**

It would be nice if the additional services were added to the index_patterns of the existing template. 
```json
 "serilog-events-template": {
    "order": 0,
    "index_patterns": [
      "netcore-service1-*",
      "netcore-service2-*",
      "netcore-service3-*"
    ],
```

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

**Comment by kimbell** [comment]
I've solved it for my use-case by calling some code before initializing serilog that uses the Elasticsearch .NET API's to create the template with the wildcard.

**Comment by mivano** [comment]
Perfect. In a recent version of the sink, you can also use your own template as part of the init phase.
