### ISSUE TITLE
Getting CustomFields Indexed by code

### ISSUE THREAD

**Issue by BoasE** [serilog/serilog-sinks-elasticsearch#189]
**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
6.5

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ x] netCore 2.0

**Please describe the current behavior?**
When I add custom fields to the logger e.g. by a logEnricher
the fields are never indexed

**Please describe the expected behavior?**
I want to get some fields always get indexed 

My Logger Config
```
   Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .Enrich.FromLogContext()
                .Enrich.With<AspRouteEnricher>()
                .Enrich.WithProperty("ServiceContext.Environment", env) // Should be indexed
                .Enrich.WithProperty("ServiceContext.Name", "FancyService") // Should be indexed
                .WriteTo.Trace()
                .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(uri)
                {
                    ModifyConnectionSettings = x =>
                    {
                        x.BasicAuthentication(user,pw");

                        return x;
                    },
                    MinimumLogEventLevel = LogEventLevel.Verbose,
                    AutoRegisterTemplate = true,
                    AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv6
                })
```

**Comment by mivano** [comment]
Are you seeing these events with properties being written by other sinks? Is it a name issue (remove the dot in the name). Did you enable selflog and notice issues with ES rejecting it?

**Comment by BoasE** [comment]
the field it self is there, the difference is that the message property isn't a custom property, its the normal log message. 

Each custom field is indexed. Mayme I should create and use a custom mapping in a file?

**Comment by BoasE** [comment]
Sorry my post is not that clear. The Problem is that only some fields are indexed and some not. 

For example the message itself is currently not indexed but some time ago when i created a test example it was automatically indexed. 
So my question is what is the intended way for indexing and when should I consider something to be indexed? 

Do I have to create a mpping fiole and use this to have a clear behavior=

**Comment by mivano** [comment]
Maybe ES is rejecting the fields? Did you look at the logs? The AutoRegisterTemplate should create a basic mapping for you. Check also the selflog of Serilog to see if the sink throws any issues.

**Comment by BoasE** [comment]
Its not rejecting when i apply my mapping with elastic endpoints its in dexed and filled

so ithere is also always the messae just not the keyword subfield

**Comment by mivano** [comment]
I might misunderstand the issue, but check the selflog of serilog first to see if the sink throws any issues.

**Comment by mivano** [comment]
Did you see anything in the selflog? Closing for now, but reopen if you have more information.
