### ISSUE TITLE
How to make message aggregateable

### ISSUE THREAD

**Issue by BoasE** [serilog/serilog-sinks-elasticsearch#191]
What version of Serilog.Sinks.Elasticsearch is affected? Please list the related NuGet package.
6.5

What is the target framework and operating system? See target frameworks & net standard matrix.
[ x] netCore 2.0

When I push data to  the ES 6 instance the message is not aggregateable and the type is string.

i want to get it aggregateable and as fair as I know therefore it must be a keyword.

I can see that ExceptionMessage is Automatically index with a aggregateable raw field.
so wherei s the difference?
![image](https://user-images.githubusercontent.com/4619513/45551599-c18c3d80-b82e-11e8-8d0a-2345e26877f7.png)

How can I achieve this ?

**Comment by mivano** [comment]
I might miss your question, but the raw field is a copy of the indexed field. However it is not tokenized etc. This might be useful when you need to access the original data and not a converted value. Take for example a username field. If that username would contain `John Smith`, then the non raw field will be split into `john` and `smith` while the .raw field contains the value `John Smith`. 
To achieve this; that is handled in the mapping which is created as part of the template. Each index has its own mapping it gets from the template.

Hope this answers your question.
