### ISSUE TITLE
Does including 'messageformat' as a default property help?

### ISSUE THREAD

**Issue by jakenuts** [serilog/serilog-sinks-elasticsearch#193]
[X] Behavior (as designed I imagine)
[X] netCore 2.0
Serlog.Sinks.Elasticsearch 6.5.0

Entirely new to Serilog so the answer here might be obvious, but at first glance is seems redundant to send the 'messageformat' field to ES as you already have the message and it's contents.  My expectation would be that a minimal amount of data would be sent, or that you could limit the fields without writing a custom json serializer. 

Thanks!

James

**Comment by mivano** [comment]
The Message Template can be a very useful field to have in your store as it gives the type of message some uniqueness. It allows you to query for all the similar events regardless the actual values. See https://blog.getseq.net/serilog-tutorial/ and under paragraph _6. Finding needles in the haystack_:

> Serilog and many of its sinks take advantage of this fact to radically improve the experience of querying and filtering log events. If the message template is preserved along with the event, then a filter like the one below can immediately exclude thousands of events from a noisy logging statement, making it easier to see the interesting events that would otherwise be drowned out:

> @MessageTemplate <> 'Processing item {ItemNumber} of {ItemCount}'
>The inverse also works - zooming in on an event type makes it possible to find all events from a single logging statement.

If you want to exclude fields, then using a custom serializer would be a good option.

**Comment by mivano** [comment]
Old issue, cleaning up. Still facing this issue, feel free to reopen.
