### ISSUE TITLE
Unexpected behaviour while using IndexDecider

### ISSUE THREAD

**Issue by simonare** [serilog/serilog-sinks-elasticsearch#194]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
Serilog.Sinks.Elasticsearch Version 6.5.0

**What is the target framework and operating system? See
- [X] netCore 2.1.4
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
 I am trying to use IndexDecider for storing RequestLogs to different Index on ElasticSearch. However, the code does not work. Basicly, It creates the new Index but does not populate in it. Instead, sink sends logs to default Index which is logstash-{0:yyyy.MM.dd}

**Please describe the expected behavior?**
The expected behavior would be to send logs into the request-log-{0:yyyy.MM.dd}

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

The configuration and code is as below:

```
  var loggerConfiguration =  new LoggerConfiguration()
                .ReadFrom.Configuration(_configuration.GetSection("Logging"))
                .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://cwlog.somehost.com:9200"))
                { 
                    IndexDecider = (e, offset) =>
                    {
                        if (e.MessageTemplate.Text.Equals("<{EventID:l}> Http Request Method: {Method} Url: {Url}"))
                        {
                            var indexName = $"request-log-{offset:yyyy.MM.dd}";
                            return indexName;
                        }

                        return $"logstash-{offset:yyyy.MM.dd}";
                    },
                    CustomFormatter = new ExceptionAsObjectJsonFormatter(true)
                });
```

```
{
          "Name": "Elasticsearch",
          "Args": {
            "nodeUris": "http://cwlog.creditwestbank.com:9200",
            //"minimumLogEventLevel": "Debug",
            "autoRegisterTemplate": true,
            "autoRegisterTemplateVersion": "ESv6",
            //"customFormatter": "Serilog.Sinks.Elasticsearch.ExceptionAsObjectJsonFormatter, Serilog",
            "bufferBaseFilename": "c:\\logs\\dev\\westapi\\es-buffer",
            "bufferFileSizeLimitBytes": 52428800,
            "period": 2,
            "bufferLogShippingInterval": 5000
          }
        }
```

ElasticSearch Log

```
{
	"request-log-2018.10.02": {
		"aliases": {
			
		},
		"mappings": {
			
		},
		"settings": {
			"index": {
				"creation_date": "1538455897529",
				"number_of_shards": "5",
				"number_of_replicas": "1",
				"uuid": "NXLTgX9JQ56HBhOywycmPg",
				"version": {
					"created": "6010299"
				},
				"provided_name": "request-log-2018.10.02"
			}
		}
	}
}
```
Please note that; the index is created but is not populated, And the logs are sent to default index.

**Comment by mivano** [comment]
Can you try with `"request-log-{0:yyyy.MM.dd}"` instead?

**Comment by simonare** [comment]
@mivano  no luck with that. the behavour is still same.

**Comment by pierresetteskog** [comment]
Indexdecider is not supported with persistant file option either. So i ended up using filters which seems to work and gives less complex code in the sink. Log.Logger = new LoggerConfiguration()
    .WriteTo.Console()
    .Filter.ByExcluding(Matching.WithProperty<int>("Count", p => p < 10))
    .CreateLogger();

**Comment by mivano** [comment]
This package should contains a fix: https://www.nuget.org/packages/Serilog.Sinks.ElasticSearch/6.5.0-alpha0045
