### ISSUE TITLE
when logging an exception the "ClassName" property remains empty

### ISSUE THREAD

**Issue by roelandvh** [serilog/serilog-sinks-elasticsearch#196]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
Serilog.Sinks.ElasticSearch, version 6.5.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**

When an exception is logged and sent to Elasticsearch, in Kibana I can see the `exceptions` property. Several subproperties in `exceptions` are filled as expected, like `Message`, `Source`, `StackTraceString`, but the property `ClassName` remains empty. This appears to be related to the fact that `NO_SERIALIZATION` is defined when compiling for netstandard1.3. (Because if `NO_SERIALIZATION` is defined, then `var className = string.Empty;` is used.)

**Please describe the expected behavior?**

I expect the `ClassName` property under the `exceptions` property to not be empty, but instead contain the full name of the type of the exception (e.g. `System.InvalidOperationException`).

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

I created a fork and I think I fixed it there (see the last 2 commits (633ae5efc19c8e5b2b64c4de192a057c88d7de9e and 338587206a101ba4d5732e03330a129a6da3f3d1) on https://github.com/roelandvh/serilog-sinks-elasticsearch) using `exception.GetType().FullName`, but I'm not sure that is a valid solution for this case (perhaps `.GetType` is too expensive in this context?).

Also I had to tweak the .csproj file to force `NO_SERIALIZATION` to be set (which I did not commit) because apparently everything was building and running as if targetting `net45`. (When I did this, the test actually failed when I removed my fix, and succeeded after re-applying the fix, so I'm confident it works as expected when `NO_SERIALIZATION` is set.)

**Comment by ffMathy** [comment]
I'm seeing this error currently. What do I have to do to apply the fix in #222 that supposedly fixes this?

**Comment by vhatsura** [comment]
Hey, @ffMathy. Which version do you use? The issue was fixed with adding target to .netstandard2.0, which was shipped in `7.2.0-alpha001` version.

**Comment by ffMathy** [comment]
Ah I see. Currently only using latest stable release. That makes sense, thanks :+1:
