### ISSUE TITLE
How to modify the ElasticsearchSinkOptions when using 'ReadFrom.Configuration'

### ISSUE THREAD

**Issue by timiil** [serilog/serilog-sinks-elasticsearch#197]
hi all,

i am using the code 
```
var logger = new LoggerConfiguration()
    .ReadFrom.Configuration(configuration)
    .CreateLogger();
```

to create the Serilog.Sinks.Elasticsearch logger, including json config just like :

```
"Serilog": {
    "WriteTo": [      
      { "Name": "Console" },      
      {
        "Name": "Elasticsearch",
        "Args": {
          "nodeUris": "http://192.168.11.196:9200",
          "indexFormat": "logstash-{0:yyyy.MM.dd}",
          "batchPostingLimit": 50,
          "period": 2000,
          "inlineFields": true,
          "minimumLogEventLevel": "Information",
          "bufferBaseFilename": "./seribuffer",
          "bufferFileSizeLimitBytes": 5242880,
          "bufferLogShippingInterval": 5000,
          "connectionTimeout": 5,
          "emitEventFailure": "WriteToSelfLog",          
          "queueSizeLimit": "100000",
          "autoRegisterTemplate": true,
          "autoRegisterTemplateVersion": "ESv2"
        }
      }
    ]
  }
```
it is work , but how can i add the FailureCallback in type 'Serilog.Sinks.Elasticsearch.ElasticsearchSinkOptions' ? 
i can not find the instance according the Log.Logger or any other way to get . any idea??

**Comment by mivano** [comment]
Unfortunately, there is no generic way besides offering all the possible options as parameters. The logic that reads the configuration will try to map it. As this sink offers a lot of different options and some of them are a bit complex (like selecting a type or specifying a function), not all of them are exposed. 

One option is to make your own subtype, add the constructor you need and call the underlying ES sink from there. Then you have full control over what you need.
