### ISSUE TITLE
The bookmark file is always empty

### ISSUE THREAD

**Issue by nicoclau** [serilog/serilog-sinks-elasticsearch#198]
Hello we need your help.

In one project we can't make serilog write properly to our elasticsearch server.

We configured the serilog sink:

 _logElastic = new LoggerConfiguration()
                .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri(elasticURI))
                {
                    MinimumLogEventLevel = LogEventLevel.Verbose,
                    BufferBaseFilename = elasticBuffer,
                    IndexFormat = "......"
                })
                .CreateLogger();

then we write:

 _logElastic.Information("RESULT-API {@Data}", data);

We get the two files 

* bookmark
* json

but the bookmark file is always empty. Can you tell us where to look?
Thanks for your help

![image](https://user-images.githubusercontent.com/16133485/48428895-4088ee00-e76c-11e8-8284-86b19ac0bc94.png)

**Comment by nicoclau** [comment]
Hello all,

I resolved the problem.

I set up the SeriLog to write debugging information.

Serilog.Debugging.SelfLog.Enable(msg => System.Diagnostics.Trace.WriteLine(msg));

We had the exception 

14/11/2018 12:47:22.646 (56;MrFly.Travel.Services.AirFaresUAPI.Program+<>c) Debug: SelfLog 2018-11-14T11:47:22.6464002Z Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.ElasticsearchLogShipper: Elasticsearch.Net.UnexpectedElasticsearchClientException: Dynamic operations can only be performed in homogenous AppDomain. ---> System.InvalidOperationException: Dynamic operations can only be performed in homogenous AppDomain..
   Ã  System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   Ã  System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   Ã  Elasticsearch.Net.DynamicBody.set_Item(String name, Object value)
   Ã  Elasticsearch.Net.DynamicBody.Create(IDictionary`2 values)
   Ã  Elasticsearch.Net.LowLevelRequestResponseSerializer.Deserialize(Type type, Stream stream)
   Ã  Elasticsearch.Net.LowLevelRequestResponseSerializer.Deserialize[T](Stream stream)
   Ã  Elasticsearch.Net.ResponseBuilder.SetSpecialTypes[TResponse](Byte[] bytes, TResponse& cs)
   Ã  Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   Ã  Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   Ã  Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   Ã  Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   Ã  Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- Fin de la trace de la pile d'exception interne ---
   Ã  Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   Ã  Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters)
   Ã  Serilog.Sinks.Elasticsearch.ElasticsearchLogShipper.OnTick()

At last, we have a clue about the problem!

It seems the dynamic variable is used by the dispatching.
But our config file has :

<NetFx40_LegacySecurityPolicy enabled="true" />

By removing this setting, it worked.

**Comment by mivano** [comment]
Thanks for the feedback, good to see you found the issue. Enabling the selflog is always a good start.

**Comment by nicoclau** [comment]
Thanks Mivano for your feedback, what surprised me was the error was not "visible".
Could you make sure the error can be available even when selflog is disabled?

I thought for example by using
  FailureCallback = e => Console.WriteLine("Unable to submit event " + e.MessageTemplate),
                    EmitEventFailure = EmitEventFailureHandling.WriteToSelfLog |
                                       EmitEventFailureHandling.WriteToFailureSink |
                                       EmitEventFailureHandling.RaiseCallback,
                    FailureSink = new FileSink("./failures.txt", new JsonFormatter(), null)

I would find the error in the failures.txt but nothing happened.
It would be good to update the code to bubble up the error in the sink so we could see this error in the failure file.

Thanks :)
