### ISSUE TITLE
save geo-point to elastic search from a C# program using serilog's elasticsearch sink.

### ISSUE THREAD

**Issue by ezmani** [serilog/serilog-sinks-elasticsearch#201]
I am attempting to put in geo_point information and other related information into elastic-search and plot it in a kibana visualiztion as a map cooardinate. I am not having success with elastic recognizing my structured class as a geopoint and wondered if there is any written C# examples that would help me do this. 

The following line is setup to write directly to elasticsearch over port 9200.

`_logger.Information("StructuredEvent, {@StructuredEvent}", structuredEvent);`

The class definition of StructuredEvent is as follows.

`public class StructuredEvent
{
    public string StoreNumber { get; set; }
    public string IpAddress { get; set; }
    public string DeviceName { get; set; }
    public bool HeartBeat { get; set; }
    public int Frequency { get; set; }
    public string Notes { get; set; }
    public DateTime LastCheckIn { get; set; }
    public location location { get; set; }
}
public class location
{
    public float lon { get; set; }
    public float lat { get; set; }
}`

I have tried to change the location class different ways to get elastic to recognize as a geo_point but it keeps showing up as number.

Any help would be much appreciated!

Thanks!
Mani

**Comment by pierresetteskog** [comment]
tell elasticsearch in an index template which field is going to hold the location.
https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html
by update the code bellow
index templates
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html
c# code to set custom index template. delete tenplete to get serilogger to recreate the template

           elasticsearchSinkOptions.GetTemplateContent = () => GetTemplateData(elasticsearchSinkOptions);

              
        

        private static object GetTemplateData(ElasticsearchSinkOptions options)
        {

            var settings = new Dictionary<string, string>
            {
                {"index.refresh_interval", "5s"}
            };

            if (options.NumberOfShards.HasValue)
                settings.Add("number_of_shards", options.NumberOfShards.Value.ToString());

            if (options.NumberOfReplicas.HasValue)
                settings.Add("number_of_replicas", options.NumberOfReplicas.Value.ToString());

            var IndexFormatRegex = new Regex(@"^(.*)(?:\{0\:.+\})(.*)$");
            var templateMatchString = IndexFormatRegex.Replace(options.IndexFormat, @"$1*$2");
            if (templateMatchString.StartsWith("log-"))
                templateMatchString = "log-*";
            return GetTemplateESv6(settings, templateMatchString);

        }

        private static object GetTemplateESv6(Dictionary<string, string> settings,string templateMatchString)
        {
            return new
            {
                template = templateMatchString,
                settings = settings,
                mappings = new
                {
                    _default_ = new
                    {
                        dynamic_templates = new List<Object>
                        {
                            //when you use serilog as an adaptor for third party frameworks
                            //where you have no control over the log message they typically
                            //contain {0} ad infinitum, we force numeric property names to
                            //contain strings by default.
                            {
                                new
                                {
                                    numerics_in_fields = new
                                    {
                                        path_match = @"fields\.[\d+]$",
                                        match_pattern = "regex",
                                        mapping = new
                                        {
                                            type = "text",
                                            index = true,
                                            norms = false
                                        }
                                    }
                                }
                            },
                            {
                                new
                                {
                                    string_fields = new
                                    {
                                        match = "*",
                                        match_mapping_type = "string",
                                        mapping = new
                                        {
                                            type = "text",
                                            index = true,
                                            norms = false,
                                            fields = new
                                            {
                                                keyword = new
                                                {
                                                    type = "keyword",
                                                    index = true,
                                                    ignore_above = 256
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        properties = new Dictionary<string, object>
                        {
                            {"message", new {type = "text", index = "true"}},
                            {
                                "exceptions", new
                                {
                                    type = "nested",
                                    properties = new Dictionary<string, object>
                                    {
                                        {"Depth", new {type = "integer"}},
                                        {"RemoteStackIndex", new {type = "integer"}},
                                        {"HResult", new {type = "integer"}},
                                        {"StackTraceString", new {type = "text", index = "true"}},
                                        {"RemoteStackTraceString", new {type = "text", index = "true"}},
                                        {
                                            "ExceptionMessage", new
                                            {
                                                type = "object",
                                                properties = new Dictionary<string, object>
                                                {
                                                    {"MemberType", new {type = "integer"}},
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            };
        }

**Comment by mivano** [comment]
Thanks @pierresetteskog for the answer. @ezmani hope this helps you. I'm closing this issue now. Feel free to reopen if you have more questions.
