### ISSUE TITLE
Add .Net Standard 2.0 target

### ISSUE THREAD

**Issue by vhatsura** [serilog/serilog-sinks-elasticsearch#210]
According to [Open-source library guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting) it would be good to target .Net Standard 2.0 to benefit from having a smaller package graph.

I would appreciate to help with it.

**Comment by mivano** [comment]
I think indeed it would be great to update the package to the latest and greatest. Unfortunately I m not using the sink at the moment. So I welcome a PR.
