### ISSUE TITLE
Question: AppSettings - Passing credentials best practice

### ISSUE THREAD

**Issue by stephenpatten** [serilog/serilog-sinks-elasticsearch#214]
Hello,

Here are the current references as of today:

  package id="Elasticsearch.Net" version="6.5.0" targetFramework="net462"
  package id="Newtonsoft.Json" version="12.0.1" targetFramework="net462"
  package id="Serilog.Formatting.Elasticsearch" version="6.5.0-alpha0057" targetFramework="net462"
  package id="Serilog.Sinks.Elasticsearch" version="6.5.0" targetFramework="net462"

Question:
I am using the app settings exclusively and have reservations about using the nodeUris property to include the userId and Password of an account with permissions to the elastic cluster. Is there a more secure way of authenticating, i.e. encrypt the keys? 

Thank you,
Stephen

**Comment by stephenpatten** [comment]
Reading through the closed issues I found [this](https://github.com/serilog/serilog-sinks-elasticsearch/issues/75). Can this still be accomplished via appSettings? 

Is this the correct app  setting ?

<add key="serilog:write-to:Elasticsearch.connectionGlobalHeaders" value="Authorization=Bearer SOME-TOKEN;OtherHeader=OTHER-HEADER-VALUE" />

or is it this

<add key="serilog:write-to:Elasticsearch.connection" value="My.Namespace.MyConnection, My.Assembly.Name" />

Thanks again for putting up with my noob questions.

**Comment by stephenpatten** [comment]
After reading even more of the closed issues I found this [PR ](https://github.com/serilog/serilog-sinks-elasticsearch/pull/90) from @AmirSasson that satisfies most of my reservations.  Thank you @AmirSasson

**Comment by mivano** [comment]
Good that you found a solution. Storing credentials in config files is not the greatest solution, but it is a tradeoff you need to consider. Best it to retrieve credentials at runtime from a secure vault like Azure Keyvault, but it depends on a lot of variables if this applies to your case. 

Still, you do need to inject it via another way than the appsettings reader even if you store them in the appsettings.
