### ISSUE TITLE
Is there a planned release for version 7.1.0?

### ISSUE THREAD

**Issue by balajisivaraman** [serilog/serilog-sinks-elasticsearch#215]
Hi,

P.S.: Not following the usual issue template since this is more of a question. (Also I asked the same question in the `Serilog` Gitter channel and was redirected to here.)

Hey, new user here, I was wondering whether version `7.1.0` of the ElasticSearch sink has been released or will be released soon?

We're currently spiking out the ES sink for use in a containerized micro-services environment where Filebeat isn't able to give us the throughput we want. Our tests show this library performing better. However, I'm interested in the changes in version `7.1.0` that are primarily around using the `RollingFileSink` to ensure that files get rolled constantly and we don't run into any issues with files eating up too much disk space.

I noticed the alpha version was released as `6.5.0-alpha57` instead of `7.1.0`. I'm currently going to be running tests against this alpha version.

If the release is made available soon, we'll be really happy.

Thank you in advance.

**Comment by mivano** [comment]
Apologies, I created a release just now and the package should be availlable: https://github.com/serilog/serilog-sinks-elasticsearch/releases/tag/v7.1.0%2B63.build.330

**Comment by balajisivaraman** [comment]
Wow! Thank you for the amazingly prompt response. :smiley:
