### ISSUE TITLE
Wrong option values

### ISSUE THREAD

**Issue by alpergunay** [serilog/serilog-sinks-elasticsearch#216]
Hi,
Although I am setting numberOfShards = 1 and numberOfReplicas = 0 at appsettings file, serilog continue to use default values 20 for the numberOfShards  and 10 for the numberOfReplicas. I attached appsettings and elasticsearch screenshots. 

```
var conf = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", reloadOnChange: true, optional: true)
                .Build();
Log.Logger = new LoggerConfiguration().ReadFrom.Configuration(conf)
                .Enrich.WithMachineName()
                .CreateLogger();

```
![image](https://user-images.githubusercontent.com/25134503/52974670-6e1cad80-33d3-11e9-9d7d-eca193e13012.png)

![image](https://user-images.githubusercontent.com/25134503/52974717-9c9a8880-33d3-11e9-913e-d5bcb171936d.png)

**Comment by mivano** [comment]
Be aware that it only applies to newly created indexes and that it needs to be available in the template mapping. So first thing to check is to see if the template has been altered to include your new settings. Then it will apply to a newly created index. You do have `overwriteTemplate` set to false in your code, so it will not update an already existing template which might be the cause of your issue.

**Comment by alpergunay** [comment]
Setting `overwriteTemplate` = true solved my issue. Thank you very much for your help.
