### ISSUE TITLE
Core Console Application not Logging

### ISSUE THREAD

**Issue by DanielClausen** [serilog/serilog-sinks-elasticsearch#217]
> Is this an issue related to the [Serilog core project](https://github.com/serilog/serilog) or one of the https://github.com/serilog/serilog-sinks-elasticsearch

**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
7.1.0

**What is the target framework and operating system? See [target frameworks]
- [X ] netCore 2.0 (2.1)
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
Console Application doesn't log to ElasticSearch

**Please describe the expected behavior?**
Log entries to ElasticSearch

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
- Create a new Console Application
- Add Nuget Packages 
  - Serilog 2.8
  - Serilog.Sinks.Console (3.1.1)
  - Serilog.Sinks.ElasticSearch (7.1.0)

Console Application Code:
```
using Serilog;
using Serilog.Formatting.Elasticsearch;
using Serilog.Sinks.Elasticsearch;
using System;

namespace ElasticConsole {
    class Program {
        static void Main(string[] args) {
            Serilog.Debugging.SelfLog.Enable(msg=> Console.WriteLine(msg));

            var logger = new LoggerConfiguration()
                  .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://elasticsearch.mydomain.com:9200")) {
                      FailureCallback = e => Console.WriteLine("Unable to submit event " + e.MessageTemplate),
                      EmitEventFailure = EmitEventFailureHandling.WriteToSelfLog |
                                       EmitEventFailureHandling.RaiseCallback,
                      AutoRegisterTemplate = true,
                      AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv6,
                      IndexFormat = "console-test-{0:yyyy.MM}",
                      MinimumLogEventLevel = Serilog.Events.LogEventLevel.Verbose,
                      CustomFormatter = new ExceptionAsObjectJsonFormatter()
                  })
                  .WriteTo.Console()
                  .CreateLogger();

            logger.Information("Hello Elastic!");
        }
    }
}
```

Run the application.  You'll see "Hello Elastic!" in the console window.  SelfLog doesn't log anything and the failureCallBack is never hit.  If I run Fiddler I see no attempts to post to POST to ElasticSearch.  I've configured Serilog and ElasticSearch in a few asp.net core web applications and it is working fine.  But so far I can't get the ElasticSearch Sink to work from any console applications and I can't get any useful debug information to come out of it.

**Comment by mivano** [comment]
Make sure you dispose the logger at the end. Your application can close too soon so it does not have time to flush its buffer to ES. So add a `logger.CloseAndFlush()`

**Comment by DanielClausen** [comment]
Thanks!  This pointed me in the right direction.  Logger doesn't appear to have CloseAndFlush in Serilog 2.8  but calling Dispose() does fix the issue.  Thanks very much for your help with this.

**Comment by DanielClausen** [comment]
After playing with this further it seems like this sink doesn't actually log anything it is disposed.  If I put a breakpoint after writing to the log it doesn't post to Elastic and if an unhandled exception is thrown it also will not write any log entries.  This isn't how any of the other sinks we've used behaves and seems to be problematic as your not going to get any logs unless everything completes and the logger is disposed.  Do I have something misconfigured?

**Comment by mivano** [comment]
So it does log after Disposing? it will buffer and do a batch upload to ES. You can change the buffer size and timing. 
Your config looks sensible and I would expect any issue to popup on the selflog.

**Comment by DanielClausen** [comment]
Ok, I see.  I wasn't aware of the buffering, that makes sense now.  Wish there was a way to toggle the buffering on or off but I think we can configure this to our liking.  Thanks again.

**Comment by mivano** [comment]
The sinks are either using a direct delivery to their service (like console of file) or use a periodicbuffer. In that case, the logevents are buffered till either 50 records or so many seconds. After that they are delivered to the end service to make it performant. So for long-running processes, this does not really matter. For short-lived console apps, you need to close and flush those buffers first.
