### ISSUE TITLE
Question: Custom configuration wrapper

### ISSUE THREAD

**Issue by stephenpatten** [serilog/serilog-sinks-elasticsearch#220]
Hello,

I posted a [question ](https://stackoverflow.com/questions/54848023)to SO  in the hopes that I could configure the sink in a more Fluent API fashion. I'm using Autofac modules to keep things organized, so I wanted to have the configuration of the logger be very simple via extension methods.

Any feedback welcome.

Thank you,
Stephen

**Comment by mivano** [comment]
I see the question was answered, hope it was enough to keep you going. If not, let's continue on SO.
