### ISSUE TITLE
[help wanted] 

### ISSUE THREAD

**Issue by Dypso** [serilog/serilog-sinks-elasticsearch#228]
I am working on a webapi 2 .Net project and I am planning to use Serilog and centralize my logs in elasticsearch with the serilog-sinks-elasticsearch library.

I am using  **serilog-sinks-elasticsearch  version 7.1.0.0**, with Framework **.Net 4.7.1**

I am using **elasticsearch in version 6.6.2** and I have read[ that the recommanded way of working with it is to declare different an index ](https://www.elastic.co/fr/blog/removal-of-mapping-types-elasticsearch)for **each document type**.

How could I declare and register a document type by index with this library ?

**Comment by Dypso** [comment]
Is this project still active ?

**Comment by mivano** [comment]
You only have one document type; the logevent. And by default, it will create an index per day for this type. So you will end up with a `logstash-2019.03.29` etc index. This makes it easy to search for log events for a specific day, or for a range (as you can specify which indexes to search through). This also makes nice with the Kibana interface. You can set a different structure by passing in an option, but the default should be fine.

BTW this also allows you to clear the data easily. For example, look at https://www.elastic.co/guide/en/elasticsearch/client/curator/current/about.html 

Does that answer your question? And yes, the project is still alive, but not that alive that with 16 hours you have an answer.

**Comment by Dypso** [comment]
@mivano, thank you for your response. Sorry I did not want to be rude.
 I think I get it : there is by default one document type with a daily index : the only problem I see is if there is a logged property with the same name but with different types (ie as string or as integer).
 
 Also, is it possible to have an index for log event, one for buisness event, and another for perf event : then I could have different retention policies for all those kind of events ? There is an indexdecider option but I have no clue how to use it.
