### ISSUE TITLE
Bug in stack trace as array of strings

### ISSUE THREAD

**Issue by AceHack** [serilog/serilog-sinks-elasticsearch#232]
https://github.com/serilog/serilog-sinks-elasticsearch/blob/f9f80778c743ea2f1d8c7eb008f171a6ed59ad28/src/Serilog.Formatting.Elasticsearch/ExceptionAsObjectJsonFormatter.cs#L54

The formatStackTraceAsArray parameter is passed to the base classes renderMessageTemplate parameter

**Comment by mivano** [comment]
@oscarmorasu I think a recent change by you? Would you mind to have a look?

**Comment by oscarmorasu** [comment]
@AceHack , that's the intended behavior. By default it's false (so it keeps the existing behavior). If set to true the new behavior kicks in.
If I don't pass the flag to the base class it would be a bug.

**Comment by mivano** [comment]
Done, thanks!
