### ISSUE TITLE
Setting NumberOfReplicas to 0 does not have any effect

### ISSUE THREAD

**Issue by ffMathy** [serilog/serilog-sinks-elasticsearch#239]
Setting `NumberOfReplicas` to 0 in the `ElasticsearchSinkOptions` does not work. Only if the value is higher.

0 should still be a valid value, and the value is also a nullable integer currently, so I think this is a bug.

**Comment by tresoldigiorgio** [comment]
it woks for me with this settings:
`
{
                    "Name": "Elasticsearch",
                    "Args": {
                        "nodeUris": "http://localhost:9200",
                        "indexFormat": "auditlog-{0:yyyy.MM}",
                        "numberOfShards": 1,
                        "numberOfReplicas": 0,
                         "overwriteTemplate": true,
                          "autoRegisterTemplate": true,
                          "autoRegisterTemplateVersion": "ESv6",
                          "numberOfShards": 1,
                          "numberOfReplicas": 0
                    }
                }
`

**Comment by ffMathy** [comment]
Not via the `ElasticsearchSinkOptions` object. I'm not talking about JSON configuration.

**Comment by ffMathy** [comment]
Example:

```
loggerConfiguration.WriteTo.Elasticsearch(new ElasticsearchSinkOptions(elasticsearchBaseUrl)
                {
                    Period = TimeSpan.FromSeconds(10),
                    NumberOfReplicas = 0,
                    NumberOfShards = 5,
                    BatchPostingLimit = 100,
                    AutoRegisterTemplate = true,
                    MinimumLogEventLevel = LogEventLevel.Verbose,
                    AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv6,
                    CustomFormatter = new ExceptionAsObjectJsonFormatter(
                        renderMessage: true,
                        serializer: new JsonNetSerializer(
                            new LowLevelRequestResponseSerializer(),
                            new ConnectionSettings(elasticsearchBaseUrl),
                            modifyContractResolver: x =>
                                x.NamingStrategy = new CamelCaseNamingStrategy(),
                            jsonSerializerSettingsFactory: () =>
                                new JsonSerializerSettings
                                {
                                    TypeNameHandling = TypeNameHandling.None
                                }))
                })
```

The above will set number of replicas to 1.

**Comment by mivano** [comment]
Strange, 0 should be valid, but looks like it marks it as null and as such outputs the default value of 1. Care for a PR?

**Comment by ffMathy** [comment]
I don't have time unfortunately :(

**Comment by mivano** [comment]
See #301 
Old issue, cleaning up. Still facing this issue, feel free to reopen.
