### ISSUE TITLE
Support Elasticsearch 2.0

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-elasticsearch#24]
Moved from: https://github.com/serilog/serilog/issues/662

> Are anyone working on upgrading the serilog-sinks-elasticsearch to use the NEST 2.0 client that supports elastic search 2.0?

**Comment by mivano** [comment]
In progress with PR https://github.com/serilog/serilog-sinks-elasticsearch/pull/23

**Comment by mivano** [comment]
Released as v3.
