### ISSUE TITLE
The typeName is not being picked up when writing to elasticsearch as a sub-logger

### ISSUE THREAD

**Issue by pmeijer** [serilog/serilog-sinks-elasticsearch#240]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
v7.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
In addition to logging for developers, I'm trying to log specific types for certain data. In the example below the `MyLoggedType`.
The code snippet below doesn't log anything when I specify `typeName: "mytype"`. However If I set it to the default "logevent" it works fine. The same holds if set `typeName` in a `WriteTo` section in a json-file.
```csharp
            var hostUri = "localhost:9000";

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(loggerConfiguration)
                .WriteTo.Logger(log =>
                {
                    log.Filter.ByIncludingOnly(Serilog.Filters.Matching.FromSource<MyLoggedType>())
                        .WriteTo.Elasticsearch(hostUri, indexFormat: "program-spec-service-{0:yyyy.MM}", typeName: "mytype");
                })
                .WriteTo.Logger(log =>
                {
                    log.Filter.ByExcluding(Serilog.Filters.Matching.FromSource<MyLoggedType>())
                        .WriteTo.Elasticsearch(hostUri, indexFormat: "program-spec-service-{0:yyyy.MM}");
                })
                .CreateLogger();

              Log.Information("Regular log message");
              var myLogger = Log.ForContext<MyLoggedType>();
              var myLoggedType = new MyLoggedType();
              myLogger.Information("Context log message {@MyLoggedType}", myLoggedType);
```

**Please describe the expected behavior?**
The message from `myLogger` should be inserted and tagged with the _type: "mytype".

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
Define any class `MyLoggedType` and try the snippet above.

**Comment by mivano** [comment]
Old issue, cleaning up. Still facing this issue, feel free to reopen.
