### ISSUE TITLE
Elasticsearch sink - rolling file functionality?

### ISSUE THREAD

**Issue by abrasat** [serilog/serilog-sinks-elasticsearch#242]
Is it possible to configure the elasticsearch sink in a similar way like the File sink, by setting properties like rollingInterval, fileCountLimit, to limit the amount of data written to elasticsearch? I would like for instance to store some logs from different applications, for the last 30-60 days (kind of historical data, in a ring buffer). Are there any samples available for the elasticsearch sink, for this functionality?

**Comment by abrasat** [comment]
Is the index lifecycle management [https://www.elastic.co/de/blog/implementing-hot-warm-cold-in-elasticsearch-with-index-lifecycle-management](https://www.elastic.co/de/blog/implementing-hot-warm-cold-in-elasticsearch-with-index-lifecycle-management) supported by the serilog elasticsearch sink?

**Comment by mivano** [comment]
No, not as such. You can override the template creation and specify the required data yourself. But the sink only tries to deliver logevents as quickly as possible to ES and does not do any tricks for maintaining it.

**Comment by yuft** [comment]
It will be nice to have the capability to define ILM policy in this think,  so we can enforce this via CD pipeline to reduce administration overhead.

*beats can define ILM policy in its configuration.
https://www.elastic.co/guide/en/beats/metricbeat/current/ilm.html

**Comment by mivano** [comment]
Old issue, cleaning up. Still facing this issue, feel free to reopen.
