### ISSUE TITLE
Logging over several days

### ISSUE THREAD

**Issue by abrasat** [serilog/serilog-sinks-elasticsearch#243]
My test .NET console application stopped sending logs to elastic search at midnight. Is there any setting that has to be configured to be able to log over several days ? Is there any internal container limitation in elasticsearch that can be influenced over the elasticsearch sink parameters  (my test application sends a log to elasticsearch every 100 msec)? In the application no special parameters were set at configuring the elasticsearch sink:

```
.WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:9200"))
{
    AutoRegisterTemplate = true
}
```

**Comment by mivano** [comment]
It should already send log data over multiple days, however, by default it will create a new index for this new day. So do you see a new index appear?

**Comment by abrasat** [comment]
You are right, thanks! The indexes were available in the kibana "management" view, I just had to add the new index patterns for the missing days. It was not obvious to me, I am doing the first learning steps with elasticsearch/kibana,..
But nevertheless, is there any size limitation for logging with serilog to elasticsearch ? I have an use-case where hundreds of logs received as tcpip messages from an embedded system approx. every 50 milliseconds should be logged to elasticsearch. The requirement is to keep the logs for the last 30 days, that means a kind of serilog rolling files functionality, but with elasticsearch. What would be the right configuration/approach for such a scenario? Does the serilog elasticsearch sink support a "batch" functionality, to send several logs at once to elasticsearch?

**Comment by mivano** [comment]
There is no size limitation in the sink, there might be a limit in your ES setup. You have to be careful in setting up your shards and replicas for sure.
The sink will batch by default. So it will collect 50 logevents or wait 2 seconds before flushing. This is configurable. The batch operation is a single http call with all the operations to be performed against ES.

Keeping retention is something you need to handle yourself. Look for the elasticsearch curator tooling. As we store events per day in a separate index, it is very easy to remove days by simply deleting indexes or to search in only the last week (using an alias specifying the set of indexes).

If you want more resiliency, then write your events as quickly as possible to a queue instead and use for example logstash to turn those events into ES. 

hope this helps

**Comment by abrasat** [comment]
Thanks for the detailed answer. Is the functionality of rolling the elasticsearch indices (to keep the logs for lets say the last 10 days) implemented inside the serilog elasticsearch sink, or can be configured in elasticsearch? I mean the creation of a new index when a new day starts, the removal of the oldest index when the max.number of rolling indices is reached.

**Comment by mivano** [comment]
Cleaning up indexes is something you need to do outside the sink and ES. But basically, it is a matter of deleting the daily index based on a pattern. ES has a tool called Curator for this: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/about.html

The creation of a new index happens due to the index name we use. So for each event we pass it through a function that returns the name based on the timestamp. By default it will use a daily pattern and as such create a new index the next day. You can alter this behaviour and return a name with only a year and month in it. But your index will be large and normally you will only want to find events for the last day or even shorter.

**Comment by abrasat** [comment]
Thank you for the information. Is it possible to configure serilog in such a way that all daily indices are stored in the same shard? Or at least for a group of daily indices. The actual implementation allocates a new shard for each daily index.

**Comment by mivano** [comment]
Nothing in Serilog or the sink itself that can do that, but use tooling like Curator or simply the ES API to do so. Changing shard size is not a simple thing to do btw as you need to rewrite the index (an index consist of one or more shards). But you can configure ES to move older indices to slower storage for example.
