### ISSUE TITLE
Logging array of object

### ISSUE THREAD

**Issue by nipua** [serilog/serilog-sinks-elasticsearch#244]
How to write to elastic array of objects? I want logging method parameters, I serialized them to  Json.
`var jsonObject = JsonConvert.DeserializeObject(log.Parameters);`
and in elastic its an empty arrays
`"MethodName": "GetUserSetting",
"Parameters": [
[
[
[
[]
],
[
[]
]
]
]
],
"ExecutionTime": "2019-05-06T20:30:16.6882724+03:00",`
but, if i send this json from postman post query, its working.  How to solve this problem?

**Comment by mivano** [comment]
Hard to say without some more details, but prefer to use the serilog destructors as they should already do this trick.
