### ISSUE TITLE
Does not work alongside NEST 7.0.0.-alpha2 IElasticClient

### ISSUE THREAD

**Issue by naymore** [serilog/serilog-sinks-elasticsearch#251]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
7.1.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**
- [x] netCore 2.0

**Please describe the current behavior?**
In another project inside the same solution we rely on NEST v7.0.0-alpha2. Because we use elastic search also for non-log-related searching capabilities.
<PackageReference Include="NEST" Version="7.0.0-alpha2" />

As soon as this package is included in the solution the ElasticSearch Serilog sink doesn't log any output anymore.

**Please describe the expected behavior?**
It still logs...

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
1. Add a reference to <PackageReference Include="NEST" Version="7.0.0-alpha2" />
2. Register a v7 ElasticClient in your Startup

```
    ElasticClient sdf = new ElasticClient();
    services.AddTransient<IElasticClient, ElasticClient>(o => sdf);
```

Somehow a separate transient or singleton v6.8 client did not interfere...

**Comment by naymore** [comment]
Update: Also true for a separately running 7.0.0-beta1 NEST client.

> Host terminated unexpectedly:System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: '!!0 Elasticsearch.Net.ElasticLowLevelClient.IndicesPutTemplateForAll(System.String, Elasticsearch.Net.PostData, Elasticsearch.Net.PutIndexTemplateRequestParameters)'.
>    at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.RegisterTemplateIfNeeded()
>    at Serilog.LoggerConfigurationElasticsearchExtensions.Elasticsearch(LoggerSinkConfiguration loggerSinkConfiguration, ElasticsearchSinkOptions options)
> 
>

**Comment by uribahbut** [comment]
is this fixed ??

**Comment by mivano** [comment]
Old issue, cleaning up. Still facing this issue, feel free to reopen.
