### ISSUE TITLE
What "My.Namespace.MyFailureSink, My.Assembly.Name" means?

### ISSUE THREAD

**Issue by lndr-ssantos** [serilog/serilog-sinks-elasticsearch#255]
I'm trying to use Serilog to send logs to Elasticsearch, but I'm having issues to send my logs. I want to configure a failure sink on appsettings, but I don't understand the document example. Can someone show me a example?

**Comment by mivano** [comment]
Old issue, cleaning up. Still facing this issue, feel free to reopen.
