### ISSUE TITLE
Logging object array

### ISSUE THREAD

**Issue by SamilMehdiyev** [serilog/serilog-sinks-elasticsearch#257]
Hi,

I have the problem with logging array of object (object[]). When I call method "Log.Write" with 3 parameters. The method structure displayed below:

`Write(LogEventLevel level, string messageTemplate, params object[] propertyValues)`

And in elastic search I saw the following:

`{"@timestamp":"2019-07-10T15:40:24.6576547+04:00","level":"Information","messageTemplate":"{@Message}{@Accumulate}","message":"\"service\"[]","Message":"service"}`

Note: I truncated above output because there was many parameters. 

But If I call the same method with the following structure
`Write<T0, T1, T2>(LogEventLevel level, string messageTemplate, T0 propertyValue0, T1 propertyValue1, T2 propertyValue2)` - then everything is displayed correctly.

Kindly ask to help me with this problem.

**Comment by mivano** [comment]
Old issue, cleaning up. Still facing this issue, feel free to reopen.
