### ISSUE TITLE
Update elasticsearch sink's template

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-elasticsearch#26]
Moved from: https://github.com/serilog/serilog/issues/549

> Quite a few changes have gone in to our reference logstash template.

**Comment by mivano** [comment]
@Mpdreamz any pointers of what you want to change here?

**Comment by Mpdreamz** [comment]
Just a general note to make sure its still in sync with:

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json

For example: logstash now disables fielddata loading for not analyzed fields.

**Comment by mivano** [comment]
Template has been updated in v5.7 to support different versions of ES.
