### ISSUE TITLE
Exception while emitting periodic batch: System.Collections.Generic.Dictionary<string,object>' does not contain a definition for 'index'

### ISSUE THREAD

**Issue by krisztiankocsis** [serilog/serilog-sinks-elasticsearch#263]
**A few questions before you begin:**

**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**

8.0.0 (ElasticSearch.Net 7.1.0)

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
Continuously throwing exceptions in self-log.
Durable storage purge, still the same.

**Please describe the expected behavior?**
No exception should be thrown.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

Aug 04 18:01:45 cloud.mis-iwork.hu miw-cloud[22528]: 2019-08-04T16:01:45.9506278Z Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogClient: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Collections.Generic.Dictionary<string,object>' does not contain a definition for 'index'
Aug 04 18:01:45 cloud.mis-iwork.hu miw-cloud[22528]:    at CallSite.Target(Closure , CallSite , Object )
Aug 04 18:01:45 cloud.mis-iwork.hu miw-cloud[22528]:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
Aug 04 18:01:45 cloud.mis-iwork.hu miw-cloud[22528]:    at Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogClient.GetInvalidPayloadAsync(DynamicResponse baseResult, List`1 payload, List`1& cleanPayload)
Aug 04 18:01:45 cloud.mis-iwork.hu miw-cloud[22528]:    at Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogClient.SendPayloadAsync(List`1 payload, Boolean first)

**Comment by dpiessens** [comment]
I did some debugging and it looks like DynamicResponse.Body now returns a dictionary type object that requires you to access it as an indexer. I made some updates and put a PR out there, but I don't have a complete test environment to trust this as a fix. See PR #264

**Comment by mivano** [comment]
I believe this is now fixed with another PR. This package should contain the fix: https://www.nuget.org/packages/Serilog.Sinks.ElasticSearch/8.1.0-alpha0001
