### ISSUE TITLE
Connection Refused When Trying to Connect to ELK Stack

### ISSUE THREAD

**Issue by VicXue** [serilog/serilog-sinks-elasticsearch#267]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
Serilog.Sinks.Elasticsearch 8.0.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
I'm currently working on an API that I want to monitor and I used this sink in order to capture log events. I have dockerized my API and used it with the ELK docker container. My API and the ELK container are running on different linux VMs, but they should be able to communicate with each other because I'm using the host network. Everything was doing fine, but after I try to connect my ELK container with another API endpoint, the sink can no longer communicate with the ELK container. With each log event generated, a HttpRequestException is thrown. 
 
>Transaction{Id: ef3ff7d44b661ae9, TraceId: 34b684c82573d41665ece3f1db047409, ParentId: null, Name: GET Home/Index, Type: request, IsSampled: True}
>Exception: System.Net.Http.HttpRequestException, Message: Connection refused
>[2019-08-22 06:26:56][Warning] - {HttpDiagnosticListenerImplBase} Failed capturing request (failed to remove from ProcessingRequests) - This Span will be skipped in case it wasn't captured before. Request: method: POST, URL: http://<IP-To-ELK-CONTAINER>:9200/_bulk

Both my ELK container and my API can be accessed by machines in the local network. 

**Please describe the expected behavior?**
API should be able to communicate with the ELK container in another machine. 

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
In Starup.cs:
```
var elasticUri = Configuration["ElasticConfiguration:Uri"];
Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri (elasticUri))
                {
                    IndexFormat = "windowsAPI-index-{0:yyyy.MM.dd}",
                    BufferBaseFilename = "./logs/buffer",
                    EmitEventFailure = EmitEventFailureHandling.WriteToFailureSink ,
                    FailureSink = new FileSink("./failures.txt", new JsonFormatter(), null)
                })
                .WriteTo.File(new JsonFormatter(), "log.json")
            .CreateLogger(); 
```
The elasticUri is simply {IP-To-ELK-Server}:9200. 
I'm not sure what exactly caused this issue and whether this is a bug, as everything with the same setting works fine. However, any suggestion on how to debug in this situation would be really appreciated. Apologize if this causes any problem.

**Comment by VicXue** [comment]
I have removed the IndexFormat option from configuration and ELK can now pick up the logstash index. However, ELK only picks up some of the first logs transmitted with correct timestamp. Other logs transmitted in a later time period somehow get merged into the existing log block with 'old' timestamp.

**Comment by mivano** [comment]
The index formatter uses the date of the logevent to move it into the right index. Also use the selflog functionality to see any issues popping up when you have errors connecting to the server.

**Comment by VicXue** [comment]
@mivano I have done some testing and it seems I had connection issues because I was using the durable mode. When I turned it off, the connection doesn't get dropped anymore.

**Comment by mivano** [comment]
Unfortunately there are some issues with the durable mode. We are even thinking about dropping this functionality. Lots of code duplication and not stable enough.
