### ISSUE TITLE
Use Seq as a FailureSink for ElasticSearch Sink

### ISSUE THREAD

**Issue by nvivo** [serilog/serilog-sinks-elasticsearch#269]
Is it possible to use the Seq sink as a Failure Sink for the elastic search sink?

I'm looking for a way to see in a single place any errors the elasticsearch sink may be experiencing across all applications.

**Comment by mivano** [comment]
Yes, that should be possible as long as it is a `ILogEventSink` and set the `EmitEventFailure` to send it to the failure sink.
