### ISSUE TITLE
minimumLogEventLevel setting does not work

### ISSUE THREAD

**Issue by SirSeven** [serilog/serilog-sinks-elasticsearch#278]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ x ] Bug

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
8.0.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ x ] netCore 2.0
- [ x ] 4.7

**Please describe the current behavior?**
When using `minimumLogEventLevel` via either xml or json based configuration (using Serilog.Settings.Configuration 3.1.0) the set value is neither checked nor used. All events are beeing sent.

**Please describe the expected behavior?**
The logged events should be checked if they are "higher" (more-important) than the given `minimumLogEventLevel`

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
- create empty project
- install Serilog
- install Serilog.Sinks.Elasticsearch
- install Serilog.Settings.Configuration
- configure something like this:
`"Serilog": {
  "MinimumLevel": "Verbose",
  "WriteTo": [
    {
      "Name": "Elasticsearch",
      "Args": {
        "nodeUris": "http://someelastic",
        "indexFormat": "i-{0:yyyy.MM.dd}",
        "minimumLogEventLevel": "Warning",
      }
    }
  ]
}`
- write Log with log level verbose or information.
- you will find your logs in the elastic search

**Issue / Solution**
This seems to be just an documentation issue. The README.md indicates to use `minimumLogEventLevel` but the correct setting is `restrictedToMinimumLevel`. This is the issue to my pull-request.

**Comment by mivano** [comment]
Merged, Thanks for the PR.
