### ISSUE TITLE
How can Serilog send a custom "_id" field to Elasticsearch

### ISSUE THREAD

**Issue by giblets** [serilog/serilog-sinks-elasticsearch#287]
We're using Serilog and have recently installed the Serilog.Sinks.Elasticsearch sink to be able to log entries to our company's Elasticsearch server.  

We want to be able to call Elasticsearch with a custom "_id" field so that we can update existing entries with additional information as our distributed transactions travel through a Saga pattern of events.  

Using a custom _id field with Elasticsearch is very easy to do in JavaScript, but the Serilog Elasticsearch Sink doesn't seem to support this.  The _id field is assembled deep in an "ElasticsearchPayloadReader", without any options to override it.  

```
        protected override void AddToPayLoad(string nextLine)
        {
            var indexName = _getIndexForEvent(nextLine, _date);
            var action = default(object);

            if (string.IsNullOrWhiteSpace(_pipelineName))
            {
                action = new { index = new { _index = indexName, _type = _typeName, _id = _count + "_" + Guid.NewGuid() } };
            }
            else
            {
                action = new { index = new { _index = indexName, _type = _typeName, _id = _count + "_" + Guid.NewGuid(), pipeline = _pipelineName } };
            }

            var actionJson = _serialize(action);
            _payload.Add(actionJson);
            _payload.Add(nextLine);
            _count++;
        }
```

Are we overlooking something?  Is there a supported way to do this?

If not, can we maybe make an assisted minimal change and put in a pull request so that the Serilog Elasticsearch Sink supports this?

**Comment by mivano** [comment]
Well, if you use the non durable version of the sink, then it wont even output an _id and is assumes the ES server creates it own ids. Why the durable version explicitly creates (a random) id I do not know.

Overriding the behaviour to introduce your own id is not possible out of the box. I do wonder if this is the best approach as this sink is primarily targeted for logging. So bulk inserts of log data, not keeping state of updating items. A serilog `LogEvent` does not have an explicit id, so you will need to keep track of this in some other way (custom prop). 

If your intent is to keep track of what happens around a specific saga, then introduce a correlation id at the start of your saga and send this one along as an additional property to all the corresponding log events. Then you can use ES to quickly filter out all events related to the same saga.

**Comment by giblets** [comment]
Thank you Michiel, using a correlation id is the approach we'll take.  Wanted to see if the other one was possible.  I'm not sure if anyone really does it that way, but it seemed like it might be useful.  

We are definitely interested in using the durable version of the sink.  We were running into the problem of the durable version continually logging the last item continually after connectivity is re-established.  I think this was fixed in September according to the below StackOverflow post, but with the version we grabbed from Nuget last week it still appeared to be doing it.  
https://stackoverflow.com/questions/57867613/duplicated-logs-when-using-serilog-sink-elasticsearch-8-with-buffer

Thanks for making the maintaining this sink!  The code was easy to download and the unit tests all worked without a hitch.  It let us examine what was going on inside of it very easily.  Thanks!

**Comment by mivano** [comment]
auto generating ids by the store itself might be easier/faster and as you normally only append, the ids should not matter that much. 

The durable part is still a bit unstable and we are even thinking about removing it at some point. Lot of duplicate code and issues.
