### ISSUE TITLE
Clarify if period is in seconds or milliseconds

### ISSUE THREAD

**Issue by erik-wramner** [serilog/serilog-sinks-elasticsearch#288]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
8.0.0 / dev

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**

I think this is a documentation bug rather than a real bug. The period option is documented both with the value 2000 (milliseconds?) and in other places with 2 (seconds?). As far as I can tell the option actually uses seconds and few applications are likely to want 2000 seconds. I used 500 and it didn't work well.

**Please describe the expected behavior?**

The documentation of the option should be consistent and clear on the unit. If it is measured in seconds then 2000 is misleading. If it is measured in seconds in some places and milliseconds in other places it should be documented where the unit is seconds and where it is milliseconds.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

Search for period on https://github.com/serilog/serilog-sinks-elasticsearch.

**Comment by panbohaha** [comment]
I spent almost hour hours to found the bugs. I download all the source code, to debug it..

**Comment by mivano** [comment]
Thanks for raising this, changed in 8.1
