### ISSUE TITLE
Add static method to flush orphaned buffers files

### ISSUE THREAD

**Issue by guillaume86** [serilog/serilog-sinks-elasticsearch#29]
My use case of this sink let me with a lot of orphaned buffer files (ASP.NET web application with an app pool creation / destruction for each version). As far as I know, there is no way at the moment to handle this exlicitly (?).

It would be nice to have a method that I can call to force the processing of buffer files (I mean buffer files not being actively used by a logger instance).

I guess a good place would be a static method on ElasticsearchSink, something like that:

    public static void FlushBuffer(ElastictsearchSinkOptions options);

The method would throw when an error occurs (not intercepted by the Serilog selflog).

Does this look ok as a new feature?
Would a PR be considered if I decide to start implementing that? (it would probably imply some refactoring to isolate the shipping logic)

**Comment by mivano** [comment]
I m not exactly sure what you want to accomplish. You mean with buffer files that you use the durable sink and see that log files are not submitted yet while your application is stopped? 
If that is the case then you might want to look at other options like sending the logs to JSON text files and use a second service like logstash to read these files and forward them to ES. Then you are not dependent on the sink.

**Comment by guillaume86** [comment]
Yes that's my problem. That's probably a good idea to do it your way, I'll give it a go.

**Comment by mivano** [comment]
You can also use a queue system to directly put the logs in, like using https://github.com/sonicjolt/serilog-sinks-rabbitmq and then use Logstash to read it from this queue if you do not want to use files.

**Comment by mivano** [comment]
Closing this now, let us know if this did not work out okay for you.
