### ISSUE TITLE
FailureSink write to elastic.

### ISSUE THREAD

**Issue by nipua** [serilog/serilog-sinks-elasticsearch#292]
Hi, I can set for `FailureSink` elastic endpoint?
For example `FailureSink = new ElasticsearchSink(elasticOptionsDebug),` elasticOptionsDebug -this option differs only index name from elasticOptions.

**Comment by mivano** [comment]
The failure sink is another implementation of an ISink so that should be the approach to take. Do set the  EmitEventFailure option to EmitEventFailureHandling.WriteToFailureSink

**Comment by mivano** [comment]
The failure sink is another implementation of an ISink so that should be the approach to take. Do set the  `EmitEventFailure` option to `EmitEventFailureHandling.WriteToFailureSink`
