### ISSUE TITLE
Can't write JObject to Elasticsearch

### ISSUE THREAD

**Issue by antonioxxl** [serilog/serilog-sinks-elasticsearch#297]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
Serilog.Sinks.Elasticsearch 8.0.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
I've tried to write object with type `JObject` from library `Newtonsoft.Json`. After writing to `Elasticserarch` this object looks like:
```
[[[[[[[]], [[]], [[]]]], [[]], [[]], [[]]]], [[]], [[]]]
```

**Please describe the expected behavior?**
Serialized object in Elasticsearch with content

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
1) Create object from this json:
```
{ 
   "message":{ 
      "error":{ 
         "ErrorCode":2,
         "Message":"Authentication required for this method",
         "RequestId":"b7350684-a15f-49d9-a643-4f8f614af815"
      },
      "apiAccount":null,
      "url":"http://api.testhost.ru/events",
      "ip":null
   }
}
```
You can do this with this command:
```
JObject message = JsonConvert.DeserializeObject<JObject>(jsonMessage);
```
2) Write variable `message` to log through `Serilog.Sinks.Elasticsearch`
3) Have a empty arrays in Elasticsearch

**Additional info**
I find how to solve this problem in Elasticsearch package [here](https://github.com/elastic/elasticsearch-net/issues/3228). But i can't using `JsonNetSerializer` in `Serilog.Sinks.Elasticsearch`. This serializer using only in `ConnectionSettings` in constructor, and i can't modified it in `ElasticsearchSinkOptions`

**Comment by mivano** [comment]
Interesting one. Unfortunately I have almost no time to look into this, but open for a PR of course. @Mpdreamz since you were involved with the referenced ticket, any input for this issue?

**Comment by Mpdreamz** [comment]
Serilog itself can not destructure `JObject` 

https://github.com/serilog/serilog/issues/1135

I think the safer default to do here is to explicitly destructure JObject:

https://github.com/destructurama/json-net

This allows you to use `JObject` with any sink.
