### ISSUE TITLE
How to prevent string fields to be analysed?

### ISSUE THREAD

**Issue by harvinders** [serilog/serilog-sinks-elasticsearch#30]
Whilst logging events in elasticsearch through serilog all the `string` fields are geeting mapped as analysed. Is there a way to prevent or take control of the mapping?

`app.config` setting is as follows

```xml
  <appSettings>
    <add key="serilog:using" value="Serilog.Sinks.Elasticsearch" />
    <add key="serilog:minimum-level" value="Debug" />
    <add key="serilog:write-to:Elasticsearch.nodeUris" value="http://localhost:9201" />
    <add key="serilog:write-to:Elasticsearch.indexFormat" value="taf-301-test-{0:yyyy.MM}" />
    <add key="serilog:write-to:Elasticsearch.autoRegisterTemplate" value="true" />
    <add key="serilog:write-to:Elasticsearch.BufferBaseFilename" value="c:\logs" />
  </appSettings>
```
Thanks

**Comment by mivano** [comment]
Set the autoRegisterTemplate to false and provide (or alter) your own mapping specification. The autoRegisterTemplate, when set to true, registers a default mapping for common fields and maps to the index format used. So every time a new index is created, it will apply the mapping.
By defining your own mapping you are free to mark whatever you want as analysed or not.

**Comment by mivano** [comment]
Hope this helped you, if not feel free to reopen.
