### ISSUE TITLE
Authentication not working on the Elastic Cloud

### ISSUE THREAD

**Issue by Mohamad-Sobhie** [serilog/serilog-sinks-elasticsearch#305]
I am using the elastic cloud, i tried all solutions when it comes to adding the authentications, i used the basic authentication but no logs are being sent and i don't see any error. 

```
var logger = new LoggerConfiguration()
            .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("https://CLOUD:9243"))
            {
                IndexFormat = "ConsoleAPP-{0:yyyy.MM.dd}",
                AutoRegisterTemplate = true,
                ModifyConnectionSettings = x => x.BasicAuthentication("username", "password")
            }).CreateLogger();
```

I also tried to test it on my Elastic cluster on AWS and Azure, nothing seems to be working, am i missing something here?

**Comment by mivano** [comment]
Tried using the selflog of Serilog? Also, index names need to be lowercase. Do not know if we force it somewhere, but try using `consoleapp` instead.

**Comment by Mohamad-Sobhie** [comment]
the issue was the capital letter, it wasn't force to lowercase. Thanks for the help

**Comment by mivano** [comment]
Good to hear, something for us to fix.
