### ISSUE TITLE
Force IndexFormat  value to lowercase

### ISSUE THREAD

**Issue by Mohamad-Sobhie** [serilog/serilog-sinks-elasticsearch#306]
when using the index format as below, the code will not show any error, yet it will not log to elasticsearch because the indexing format should be lowered-case. This should be handled somewhere.          
```
    var logger = new LoggerConfiguration()
            .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:9200"))
            {
                IndexFormat = "TESTING",
            }).CreateLogger();
```

**Comment by mivano** [comment]
Is fixed in dev branch, will go to master soon. Tx.
