### ISSUE TITLE
Log files json split in differents files even when 2kb in size

### ISSUE THREAD

**Issue by nicoclau** [serilog/serilog-sinks-elasticsearch#309]
Hello all,
we have several log files of small size 2kb

xxx.bookmark
xxx-20200114_002.json   2kb
xxx-20200114_003.json   2kb

Why do we have several files of 2kb so small?

Context: Our code creates several instances of one class which creates one instance of logger.

Where do we need to look at : Serilog or EL sink ?

The code we used to create the logger is : 

` lock (_lock)
            {
                _logElastic = new LoggerConfiguration()
                    .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri(elasticURI))
                    {
                        MinimumLogEventLevel = LogEventLevel.Verbose,
                        BufferBaseFilename = elasticBuffer,
                        IndexFormat = "myindex-{0:yyyy.MM.dd}",
                        BufferLogShippingInterval = TimeSpan.FromSeconds(60),
                    })
                    .CreateLogger();
            }`

Thank for your help
Nico

**Comment by nicoclau** [comment]
It seems linked to the fact the logger was created several times

https://github.com/serilog/serilog/issues/531

Do I have make sure to use a singleton for the logger  ?

Can you confirm @mivano ? Thanks

**Comment by mivano** [comment]
Correct, create a logger instance at startup and use the Logger.Log static instance or add to your DI framework.

**Comment by nicoclau** [comment]
Thanks for your help.
