### ISSUE TITLE
Why has support for .NET 4.5.2 been removed?

### ISSUE THREAD

**Issue by PolarbearDK** [serilog/serilog-sinks-elasticsearch#313]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x ] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
8.0.x

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ x] 4.5.x

**Please describe the current behavior?**
Previous version had support for 4.5.x but was removed 7 months ago in commit 81ad8899e81962cb08bd7d8ea945375a64175551.

**Please describe the expected behavior?**
.NET 4.5.2 is supported until 2023 and all other nuget packages in the serilog ecosystem seems to  support 4.5.2.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
Try to install Serilog.Sinks.ElasticSearch in a 4.5.2 project.

Upgrade to 4.6.1 is unfortunately not an option in our case.

**Comment by PolarbearDK** [comment]
I'm going to answer my own question: Elasticsearch.NET has dropped support for 4.5.x :(

**Comment by mivano** [comment]
Sorry, but yes, that is the reason we dropped it as well.
