### ISSUE TITLE
exception is occuring when elastic server is missing

### ISSUE THREAD

**Issue by Su-s** [serilog/serilog-sinks-elasticsearch#316]
Below is the code for serilog elastic search.It's working perfectly when elastic service is running but fails when the server is not available

```
  .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:9200/")) // humio elastic bulk endpoint
                            {
                                AutoRegisterTemplate = true,
                                OverwriteTemplate = true,
                                DetectElasticsearchVersion = true,
                                AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv7,
                                NumberOfReplicas = 1,
                                NumberOfShards = 2,
                                RegisterTemplateFailure = RegisterTemplateRecovery.FailSink,
                                FailureCallback = e => Console.WriteLine("Unable to submit event " + e.MessageTemplate),
                                EmitEventFailure = EmitEventFailureHandling.WriteToSelfLog |
                                                   EmitEventFailureHandling.WriteToFailureSink |
                                                   EmitEventFailureHandling.RaiseCallback,
                                //FailureSink = new FileSink("./fail-{Date}.txt", new JsonFormatter(), null, null)
                                //ModifyConnectionSettings = x => x.BasicAuthentication(username: "", password: "88WS28JEuB0G2WC3cYufdgTINAxOGQvliBrqH5Vqutjb")  // password is ingest token from humio
                            })
```

exception is occuring when elastic server is missing

Elasticsearch.Net.ElasticsearchClientException: 'No connection could be made because the target machine actively refused it.. Call: Status code unknown from: GET /_cat/nodes?h=v'
 
    HttpRequestException: No connection could be made because the target machine actively refused it.
    SocketException: No connection could be made because the target machine actively refused it.
 
    This exception was originally thrown at this call stack:
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
    System.Net.Http.ConnectHelper.ConnectAsync(string, int, System.Threading.CancellationToken)

**Comment by mivano** [comment]
Failing at the registration of the template due to not finding the server and you have the RegisterTemplateFailure set to fail the sink. In that case, it will indeed raise an exception so you know your template registration is potentially not correct. 

So I m not sure what your issue is about as this is excepted behaviour.

**Comment by LucidObscurity** [comment]
I have a similar situation which I've nailed down to "DetectElasticsearchVerion = true". When this is set, failure to contact elasticsearch will throw and fail the app from starting. No combination of RegisterTemplateFailure, FailureSink & EmitEventFailure will prevent the app from crashing. Those options only appear to work when manually setting AutoRegisterTemplateVersion and DetectElasticsearchVersion = false.

**Comment by mivano** [comment]
@LucidObscurity thanks for the pointer. I created a PR to address this issue. Care to have a look if this is what you mean?

**Comment by LucidObscurity** [comment]
Thanks @mivano! The selflog upon failure is exactly what I would intuitively expect.

**Comment by mivano** [comment]
Perfect, will merge the PR. Thanks!
