### ISSUE TITLE
Access Logs wiki page is incomplete

### ISSUE THREAD

**Issue by ginomessmer** [serilog/serilog-sinks-elasticsearch#317]
I looked at the readme file and wanted to navigate over to [this page](https://github.com/serilog/serilog-sinks-elasticsearch/wiki/access-logs) but there's nothing useful. Did someone suffer from a stroke? 🤔

**Comment by mivano** [comment]
Hmm, strange indeed. Removed. Thanks for the mention.

**Comment by ginomessmer** [comment]
@mivano You might also want to remove the reference from the readme file in the 'More information' section: https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/README.md#more-information

**Comment by mivano** [comment]
Check, removed.
