### ISSUE TITLE
Where to get release files for v2.0.80

### ISSUE THREAD

**Issue by tinonetic** [serilog/serilog-sinks-elasticsearch#321]
**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
2.0.80
https://www.nuget.org/packages/Serilog.Sinks.ElasticSearch/2.0.80

**What is the target framework and operating system? See [target frameworks]
- [ ] 4.0.x

**Please describe the expected behavior?**

Would like old reference code for the package that supports .Net 4.0 (v 2.0.80)
We have an very old legacy app that we cannot upgrade at the moment, but would like to add logging to Elasticsearch.

I am well aware and researched that for .Net 4.0, the last versions supporting it are:
- Serilog 1.5.14
- Serilog.Sinks.Elasticsearch 2.0.80

I just need direction on how to get the 2.0.80 tests/code/samples for Serilog.Sinks.Elasticsearch
I managed to get the code for Serilog https://github.com/serilog/serilog/releases/tag/v1.5.14

**Comment by SeppPenner** [comment]
You might use the dll from the nuget package and analyse it with https://github.com/0xd4d/dnSpy...

**Comment by tinonetic** [comment]
Been a while but still helpful. Thanks, @SeppPenner!

**Comment by mivano** [comment]
If I look at the dates of the packages, then I think it is this commit: https://github.com/serilog/serilog-sinks-elasticsearch/commit/ecdf748d830c2be2c43a6795fbfbb0fdb7cdeac6
Maybe that helps to get a version of the code that is linked to that package, or at least generate your own package.
