### ISSUE TITLE
ILogger.Write with Elasticsearch Sink creates an 'invalid-200' file

### ISSUE THREAD

**Issue by kdavis** [serilog/serilog-sinks-elasticsearch#326]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**

Version 8.0.1 from NuGet

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 3.1
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**

Creates a file called `invalid-200-<guid>.json` file with the contents of what would be sent.

**Please describe the expected behavior?**

Write the log to ElasticSearch.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

- Create a project using ElasticSearch which registers the logger
- Try and log using `ILogger.Write(level, message)` to log a message

**My issue**

I'm trying to write a log with a varying log level

```csharp
var message = "Hello, world!";
var level = LogEventLevel.Information;
if (x == 0)
    level = LogEventLevel.Warning;

logger.Write(level, "This is a test - {message}");
```

However, using the .Write method doesn't log to Elasticsearch and instead writes a new file `invalid-200-<random guid>.json` with the contents of the log message intented for Elasticsearch.

```
{"index":{"_index":"test-2020.04.23","_type":"test-event","_id":"5_f827f06b-9f3e-48bf-b7d1-fea011a31f82"}}
{"@timestamp":"2020-04-23T13:31:54.3229080+01:00","level":"Information","messageTemplate":"This is a test - {message}","message":"This is a test - \"Hello, world!\"","message":"Hello, world!"}
```

Other logs however, written with the same logger in the same method using `Warning` or `Information` work perfectly. Just not `Write` allowing for varying levels...

**Comment by mivano** [comment]
How did you setup the logger? Looks like you use the buffer and it is not sending it to ES.

**Comment by kdavis** [comment]
I'm using `appsettings.json` for the ASP Net Core host.
```json
{
  "AllowedHosts": "*",
  "Serilog": {
    "MinimumLevel": "Verbose",
    "Enrich": ["FromLogContext", "WithExceptionDetails"],
    "WriteTo": [
      {
        "Name": "Console"
      },
      {
        "Name": "Elasticsearch",
        "Args": {
            "nodeUris": "http://localhost:9200",
            "indexFormat": "test-{0:yyyy.MM.dd}",
            "typeName": "test-event",
            "inlineFields": true,
            "autoRegisterTemplate": true,
            "bufferBaseFilename": "./buffer",
            "bufferFileSizeLimitBytes": 1024000,
            "connectionTimeout": 30
        }
      }
    ]
  }
}
```

Then creating the logger in Program.cs

```
		public static IConfiguration Configuration { get; } = new ConfigurationBuilder()
			.SetBasePath(Directory.GetCurrentDirectory())
			.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
			.AddJsonFile($"appsetings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production"}.json", optional: true)
			.Build();

		public static void Main(string[] args)
		{
			Log.Logger = new LoggerConfiguration()
				.ReadFrom.Configuration(Configuration)
				.CreateLogger();

			CreateHostBuilder(args).Build().Run();
		}
```

**Comment by mivano** [comment]
try removing the bufferBaseFilename and see if that does work. Also, enable the serilog selflog functionality. That will show you any errors in the sinks.

**Comment by kdavis** [comment]
I removed the buffer that only affected

I enabled SelfLog to console with `Serilog.Debugging.SelfLog.Enable(Console.Error);` as I wasn't sure how to enable SelfLog from a configuration file.

I got this result from the console:

```
2020-04-24T13:18:10.7885180Z Received failed ElasticSearch shipping result 400: System.Collections.Generic.Dictionary`2[System.String,System.Object]. Failed payload : {"@timestamp":"2020-04-24T14:18:06.9235640+01:00","level":"Information","messageTemplate":"This is a test - {message}","message":"This is a test - \"Hello, world!\"","message":"Hello, world!"}.
2020-04-24T13:18:10.7885920Z Received failed ElasticSearch shipping result 400: System.Collections.Generic.Dictionary`2[System.String,System.Object]. Failed payload : {"@timestamp":"2020-04-24T14:18:09.7638820+01:00","level":"Verbose","messageTemplate":"This is a test - {message}","message":"This is a test - \"Hello, world!\"","message":"Hello, world!"}.
2020-04-24T13:18:10.7905580Z HTTP shipping failed with 200: Successful (200) low level call on POST: /_bulk; dumping payload to /Users/user/Documents/Projects/project/src/Project.Server/invalid-200-9b18c8524bb14b19b093155d5765a830.json
```

The rest of the logs that use `logger.Information()` or `logger.Verbose()` work absolutely fine and end up in ElasticSearch.

**Comment by kdavis** [comment]
Any reason why `.Write` is causing the above but not `.Verbose`?

**Comment by mivano** [comment]
That is indeed strange. The `.Write` is called from the `.Verbose`  (https://github.com/serilog/serilog/blob/dev/src/Serilog/Log.cs#L264) 
Can you see the logs from your ES server and see why it is returning the 400?

**Comment by kdavis** [comment]
I had assumed it was an issue with ElasticSearch Sink because it was coming through fine in the console. I've learnt two issues while trying to fix this.

Having `{message}` in the field does not work as it creates another field called 'message' when one already exists:

```
"level":"Verbose","messageTemplate":"This is a test - {message}","message":"This is a test - \"Hello, world!\"","message":"Hello, world!"} 
```

In addition, there's an issue with putting a dash, `-`, in the message template for some unknown reason with Elasticsearch on their side.

Basically, a non-issue

**Comment by mivano** [comment]
Ah yes, duplicate property name here. Good that you were able to find the issue and thanks for reporting it. Unfortunately it is hard to fix. Same with sending a property with the same name as a integer first and in the same index use the same property name with a string.

**Comment by ArneMancofi** [comment]
@mivano , what does 
> sending a property with the same name as a integer first and in the same index use the same property name with a string

mean exactly?
I am asking because we are getting the same `invalid-200-*.json` error files with log payloads like
```json
{
  "@timestamp": "2020-04-23T10:48:14.3806376+02:00",
  "level": "Information",
  "messageTemplate": "Found {0} unhandled items",
  "message": "Found 0 unhandled items",
  "fields": {
    "0": 0,
    "applicationName": "***REDACTED***",
    "assemblyInfo": "1.1.1.0",
    "production": false,
    "company": "***REDACTED***"
  }
}
```

**Comment by ArneMancofi** [comment]
...is or real problem perhaps that another logging sent a message parameter
```
"fields": {
  "0": "foo",
  ...
}
```
where the type of field "0" is not an int?

**Comment by mivano** [comment]
ES creates mappings automatically when it first creates an index. So everyday it has a new index (using the default index format). Every field you send to it will be mapped. So when you first send a "0" field with a value of 1, ES will make this a numeric field (for that index and field name). The next time you send the same field "0" with a string value, it will fail to convert the string to a numeric value. 

For this reason, the default template will force "0", "1" fields etc (so the ones normally used in a string.format) to be strings. Conversion will work fine. For other fields it is more complicated. When you send a property called `User` with a string value and then send the same property `User` with an object, there is no way for ES to make this conversion. And since ES acts not on the row level (so each row can have its own fields and types), but does this on the index level, you run into this issue.

One solution is to be conscious of the fields you send. Another one is to use a specific JsonSerializer where the fieldname will be combined with the type name. So it becomes a unique set. User_String and User_Object for example. 

I have not used the sink for a long time myself, so there might be other solutions nowadays that I do not know of, but this was an issue. See https://stackoverflow.com/questions/26930587/elasticsearch-mapping-different-data-types-in-same-field for possible other solutions.

**Comment by ArneMancofi** [comment]
Thank you very much, @mivano, for this very useful explanation, that makes total sense. 👍 
Do you happen to know which version of the software the forcing of string type for the "0", "1", etc. fields was introduced?

**Comment by mivano** [comment]
That is really some while back already. Version 2 I think. This code (although moved) contains that logic: https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchTemplateProvider.cs#L89
