### ISSUE TITLE
ElasticsearchJsonFormatter does not allow dots when writing to kibana

### ISSUE THREAD

**Issue by rajmondburgaj** [serilog/serilog-sinks-elasticsearch#332]
This is basically to remove the old behavior of not allowing dots in the variable names.
The problem relies [here](https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/src/Serilog.Formatting.Elasticsearch/ElasticsearchJsonFormatter.cs#L154). I am not sure when ELK started to allow dots in the variable names but I can confirm that now in v7.x works fine with a dot(also in v6.x). One solution is to completely remove the logic or put a condition to only apply for old ELK versions to preserve the compatibility. If you want I can make the change for you but just let me know which option to choose in this case?

Currently in my code I created a child class from ElasticsearchJsonFormatter and customized myself, so, it works fine but since this is a bug to my eyes I wanted to fix it here as well!

**Comment by mivano** [comment]
Sorry for the late response, I m not using the sink actively anymore. But yes, this should be fixed. If v6 and up do support this, we should just remove this, document it as a change and proceed with the new behaviour. If you can make a PR and a remark in the changes.md, then much appreciated!

**Comment by rajmondburgaj** [comment]
This is already done, therefore closing the ticket.
