### ISSUE TITLE
Adding property with dot in name doesn't work

### ISSUE THREAD

**Issue by Belorus** [serilog/serilog-sinks-elasticsearch#354]
```
if (Agent.IsConfigured && Agent.Tracer?.CurrentTransaction != null)
            {
                logEvent.AddOrUpdateProperty(propertyFactory.CreateProperty("transaction.id", Agent.Tracer.CurrentTransaction.Id ));
                logEvent.AddOrUpdateProperty(propertyFactory.CreateProperty("trace.id", Agent.Tracer.CurrentTransaction.TraceId ));
            }
```

Dots in field names are escaped, and therefore it's impossible to send `trace.id` field to employ APM log correlation without writing custom JSON Serializer. It is written as `trace/id`

https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/src/Serilog.Formatting.Elasticsearch/ElasticsearchJsonFormatter.cs#L154

**Comment by mivano** [comment]
I just merged PR https://github.com/serilog/serilog-sinks-elasticsearch/pull/351 into dev. That should address this issue.
