### ISSUE TITLE
Microservice is not logging to Elasticsearch on a different server

### ISSUE THREAD

**Issue by Credak** [serilog/serilog-sinks-elasticsearch#369]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
5.4.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**

I have setup 2 Windows Server, one where my API is running and is logging all the requests and the other one has Kibana and Elasticsearch installed. So I configured it all locally with Docker where it works fine but outside of docker I cant even create an Index because it isn't sending logs to the other server.

**Please describe the expected behavior?**
I can send logs to my Elasticsearch on my other Server.

This is my Configuration Class: 
```
private static string DefaultElastichsearchUrl = "http://localhost:9200";

        public static Logger Create(IConfiguration configuration)
        {
            var elasticsearchSection = configuration.GetSection("Elasticsearch");
            if (elasticsearchSection != null)
            {
                return CreateLoggerConfiguration(elasticsearchSection).CreateLogger();
            }
            return null;
        }

        private static LoggerConfiguration CreateLoggerConfiguration(IConfigurationSection section)
        {
            var loggerConfiguration = new LoggerConfiguration();

            var url = section.GetValue<string>("Url");
            var minimumLogLevel = section.GetValue<string>("MinimumLogLevel");
            var minimumLogEventLevel = section.GetValue<string>("MinimumLogEventLevel");

            SetLoggerConfigurationMinimumLogLevel(minimumLogLevel, loggerConfiguration);

            loggerConfiguration.WriteTo.Elasticsearch(new ElasticsearchSinkOptions(GetLoggingUri(url))
            {
                MinimumLogEventLevel = ReturnLogEventLevel(minimumLogEventLevel),
                AutoRegisterTemplate = true
            });
            loggerConfiguration.Enrich.FromLogContext();

            return loggerConfiguration;
        }

```

and this is my startup.cs

```
        public Startup(IConfiguration configuration, IHostingEnvironment environment)
        {
            Configuration = configuration;
            Environment = environment;

            if (configuration != null)
            {
                Logger logger = ElasticSearchLoggerHelper.Create(Configuration);
                if(logger != null) {
                    Log.Logger = logger;
                }
            }
        }
...

        public void ConfigureServices(IServiceCollection services)
        {

            services.AddLogging(loggingBuilder => loggingBuilder.AddSerilog(dispose: true));
```

Do I have to log those to an own file? Am I missing some additional configurations???
any Ideas why this isnt working properly are appreciated...

**Comment by mivano** [comment]
There is a lot that can go wrong here; but to troubleshoot; can you connect to your deployed ES server using for example curl? So no firewall blocking? 
Next, enable selflog so you can see if and why serilog and the sink cannot connect. This might help in finding out where it is blocked.

**Comment by Credak** [comment]
No worries we fixed it already. Was some Networksetting stuff...works great now.  Thanks for your help anyways :)
