### ISSUE TITLE
Exceptions as an array breaks Kibana usage

### ISSUE THREAD

**Issue by driis** [serilog/serilog-sinks-elasticsearch#37]
A recent commit https://github.com/serilog/serilog-sinks-elasticsearch/commit/010af25d1641b009afbe47b15bc46fc7b4a070f9 changes the behaviour from writing exceptions to ES from writing an object in the "exception" field into writing an array of exceptions in "exceptions".

This breaks Kibana dashboards based on the ES logging, since Kibana doesn't play well with arrays. For instance we can't put exception.message on a dashboard.

While I understand the reason for making the change is probably to avoid deep nesting in the case of innerExceptions, I think it'd be beneficial to keep a single exception object in the "exception" field.

I'd love to provide a pull request for this, if we can agree on what behaviour it should have ? Perhaps make it configurable so users can configure the sink to use the old or new behaviour ?

**Comment by mivano** [comment]
This has indeed been a deliberate choice. See here https://github.com/serilog/serilog/issues/394
You can query for the initial exception by including the depth = 0 condition. 
Storing it double would not be very efficient, but I see what you want to accomplish. Maybe @Mpdreamz has a good tip?

**Comment by finnmich** [comment]
Is it possible to use the ExceptionAsJsonObjectFormatter when using the appSettings reader?

**Comment by michaelclark34** [comment]
Can you use tht in the appsettings?
