### ISSUE TITLE
Delete request returns an exception

### ISSUE THREAD

**Issue by DTissot** [serilog/serilog-sinks-elasticsearch#385]
- [x ] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
8.0.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

-[x] netCore 3.1
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
I'm trying to do a simple Delete, but using the already specified version of this client with Elasticsearch 7.11.0, I get a message in the OriginalException field telling me the request I'm trying to do does not support having a body.
Here's the message:
[Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: DELETE /myindex/_doc/myDocKey ServerError: Type: illegal_argument_exception Reason: "request [DELETE /myindex/_doc/myDocKey] does not support having a body"

I figured it could be some type of version-related incompatibility

**Please describe the expected behavior?**
The delete request returns a successful response

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

**Comment by mivano** [comment]
A delete verb with a body is not common and in some cases is rejected, but I m wondering where in the sink you try to do a delete operation?

**Comment by DTissot** [comment]
Thank you very much for your response!
I'm sorry. I thought the problem I was having was related to the sinks but it turned out it certainly was a versioning problem but with the version of NEST package I was using.
Sorry for any inconvenience!
