### ISSUE TITLE
How to track Elastic connection errors?

### ISSUE THREAD

**Issue by djsowa** [serilog/serilog-sinks-elasticsearch#389]
Hi,

Trying to setup Elastic sink, using following config:

```
 Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Information()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
            .Enrich.FromLogContext()
            .WriteTo.Console()
            .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://odfe-node1:9200"))
            {
                AutoRegisterTemplate = true,
                IndexFormat = "test-api-{0:yyyy.MM}",
                ModifyConnectionSettings = x => x.BasicAuthentication("admin", "admin").ThrowExceptions(true),
                FailureCallback = e => Console.WriteLine($"Unable to submit event - " + e.MessageTemplate),
                EmitEventFailure = EmitEventFailureHandling.ThrowException |  EmitEventFailureHandling.RaiseCallback,
                BufferCleanPayload = (failingEvent, statuscode, exception) =>
                {
                    dynamic e = JObject.Parse(failingEvent);
                    return JsonConvert.SerializeObject(new Dictionary<string, object>()
                    {
                        { "failingStatusCode", statuscode},
                        { "failingException", exception}
                    });
                },
            })
            .CreateLogger();
```

**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**

8.4.1

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**

> Unable to submit event - Starting host
> Unable to submit event - Starting host
> Unable to submit event - Using an in-memory repository. Keys will not be persisted to storage.
> Unable to submit event - Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
> Unable to submit event - No XML encryptor configured. Key {KeyId:B} may be persisted to storage in unencrypted form.

**Please describe the expected behavior?**

> Unable to submit event - Starting host - because http 403 or something

Can't find any way to find what kind of issue I've got, why u don't return error from Elasticsearch or do something similar?

**Comment by djsowa** [comment]
There is also second issue, when I set `EmitEventFailure = EmitEventFailureHandling.ThrowException ` I can't see any exceptions, I also set `ThrowExceptions()` for connection object. With same result :(

**Comment by djsowa** [comment]
It's WebApi, on core 3.1

I do flush in finally block as it's described in docs.
How to use selflog, where I can find examples?

**Comment by djsowa** [comment]
Using SelfDebug, I've got this exception:

> Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.ElasticsearchSink: Elasticsearch.Net.ElasticsearchClientException: An error occurred while sending the request.. Call: Status code unknown from: POST /_bulk
>  ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
>  ---> System.IO.IOException: The response ended prematurely.
>    at System.Net.Http.HttpConnection.FillAsync()
>    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at Serilog.Sinks.Elasticsearch.ElasticsearchSink.HandleException(Exception ex, IEnumerable`1 events)
>    at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatchAsync(IEnumerable`1 events)
>    at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()

I was able to track and fix configuration issue, but I think u can improve error handling in the sink, so in case of similar issues your sink can produce some error. Second suggestion is to include nullable Exception type parameter to _FailureCallback_.

**Comment by IdpugantiSanjay** [comment]
@djsowa How did you fix the issue

**Comment by djsowa** [comment]
@IdpugantiSanjay I use SelfLog to track error details:

`Serilog.Debugging.SelfLog.Enable(msg => Console.WriteLine(msg));`
