### ISSUE TITLE
Expose DurableElasticsearchSink and/or provide a method to build a sink given provided options

### ISSUE THREAD

**Issue by guillaume86** [serilog/serilog-sinks-elasticsearch#40]
It's a bit misleading that `new ElasticsearchSink()` ignores the "BufferBaseFilename" parameter (which turns on the durable mode).

I discovered it because I'd like to build a new DurableElasticsearchSink instance and the the only way seems to be through the extension method (which directly attach the sink to the logger configuration so I can't get the ILogEventSink).

**Comment by mivano** [comment]
The durable sink is based on the Seq client version and although it does what it needs to do, it is implemented in a way that makes swapping it out a bit difficult. Open for suggestions/PR.
