### ISSUE TITLE
App/Web Config documentation

### ISSUE THREAD

**Issue by zihotki** [serilog/serilog-sinks-elasticsearch#44]
Currently there is very little documentation of what properties a user can set in a config and it's very frustrating for newcomers to setup the configuration. Documentation should be improved either by mentioning where that information can be found or with actual information.

**Comment by mivano** [comment]
There is information about the config here https://github.com/serilog/serilog-sinks-elasticsearch/wiki/Configure-the-sink
What are you missing?

**Comment by zihotki** [comment]
Initially it wasn't clear which settings can be set via app config. The important remark "As there is no simple method extension that does not expect a complex type, it is not possible to use the appSettings reader for this. You need to register this sink via code." appears at the bottom of the Home doc and it can be easily missed like it was in my case. I think it's better to add a few words in bold to the configuration page as well.

**Comment by mivano** [comment]
Fair point, I added it to the config page. Thanks.
