### ISSUE TITLE
Not supporting .NetCoreApp1.0

### ISSUE THREAD

**Issue by rohitshrivastava04** [serilog/serilog-sinks-elasticsearch#48]
Hello 

Is there any plan to add support for .Net Core?

Thanks
Rohit

**Comment by mivano** [comment]
There was (https://github.com/serilog/serilog-sinks-elasticsearch/pull/21) but it needs follow up.

**Comment by Mpdreamz** [comment]
Elasticsearch.NET supports .net core rtm from `2.4.1` when #53 lands adding suport should be relatively straight forward.

**Comment by merbla** [comment]
Just an FYI, just adding ES over [here](https://github.com/merbla/serilog-docker/tree/elastic-search) and I am getting the following with the `4.0.142 ` package.

```
consoleapp_1     | /sample/project.json(9,44): error NU1002: The dependency Serilog.Sinks.Elasticsearch 4.0.142 does not support framework .NETCoreApp,Version=v1.0.
consoleapp_1     |
consoleapp_1     | Compilation failed.
```

**Comment by Mpdreamz** [comment]
Yep this sink is not compatible just yet, i've started a local branch to move the project over to the dotnet tooling and start building against netstandard1.3. Expect to open a PR today or tomorrow

**Comment by C-4** [comment]
Hi, any idea when this PR will be opened / .netcoreapp1.0 support will be ready?

**Comment by chrispaynter** [comment]
Thanks @Mpdreamz, looking forward to this.

**Comment by Hossrod** [comment]
@Mpdreamz , thanks for working on this!

We are moving to .NET Core and serilog elasticsearch is the last piece I need to get working. Any update when you think you might have this?

**Comment by Hossrod** [comment]
@Mpdreamz, oh and if you want to release as a pre nuget or something, I would be happy to do some testing of it and report back.

**Comment by mivano** [comment]
dotnet core support has been added. Please reopen the ticket if you still have issues. tx

**Comment by Hossrod** [comment]
Thanks! Just installed 4.1.0 via nuget and working good so far in .NET Core app.
