### ISSUE TITLE
Tag releases and include AssemblyInformationalVersion attribute with commit hash code

### ISSUE THREAD

**Issue by zihotki** [serilog/serilog-sinks-elasticsearch#49]
Tagging releases allows to find the commit from which some specific version of the library was built from the git side. AssemblyInformationalVersion with commit hash code also helps with that too. It's better to include both of the options to give more flexibility. The attribute looks like this:

[assembly: AssemblyInformationalVersion("1.3.1.74-g23246c2")]

**Comment by mivano** [comment]
Good idea, care to submit a PR for this?

**Comment by LordMike** [comment]
https://github.com/AArnott/Nerdbank.GitVersioning

**Comment by mivano** [comment]
Old issue, cleaning up
