### ISSUE TITLE
Help, is there any sample project to use this sink?

### ISSUE THREAD

**Issue by rohitshrivastava04** [serilog/serilog-sinks-elasticsearch#50]
I am pretty sure, I am doing something wrong.

I have created a new project added Serilog and Serilog.Sinks.Elasticsearch nuget packages.

When I run I face following error

"An unhandled exception of type 'System.IO.FileNotFoundException' occurred in LogConsole.exe

Additional information: Could not load file or assembly 'Serilog.FullNetFx, Version=1.5.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies. The system cannot find the file specified."

I have .Net Core RC2 installed on my machine, I suspect it could be related to that but not sure.

`var loggerConfig = new LoggerConfiguration()
                .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:80"))
                {
                    AutoRegisterTemplate = true,
                });
            Log.Logger = loggerConfig.CreateLogger();
            LogMessage message = new LogMessage();
            Log.Information("{@message}", message);
            Console.ReadKey();`

**Comment by mivano** [comment]
Please use the latest version of the sink as this has .net core support. If the problem still occurs, feel free to reopen.
