### ISSUE TITLE
When using Buffer-files the callback to IndexDecider is fired with an empty LogEvent.

### ISSUE THREAD

**Issue by KennyEliasson** [serilog/serilog-sinks-elasticsearch#52]
```
new ElasticsearchSinkOptions(new Uri(elasticSearchUri)) {
                    BufferBaseFilename = elasticSearchBufferFolder,
                    IndexDecider = (ev, offset) =>
                    {
                        return string.Format("{0}-{1}", "logs", ev.LogEvent.ToString(), offsetDate);
                    }
};
```

Row 163 in ElasticSearchLogShipper is passing in null.

```
var indexName = _state.GetIndexForEvent(null, date);
```

What we're trying to accomplish is reading out the LogLevel of the event and creating indices upon that so we can have different retention policies on fatal/errors and info/debug. Maybe there is another way to accomplish that?

**Comment by guillaume86** [comment]
An simple fix would be to call the index decider when writing in the buffer and prepending it to each record, then read it when shipping (stop at `{` or use a customizable separator in case someone use a custom serialization format).

**Comment by mivano** [comment]
Old issue, cleaning up
