### ISSUE TITLE
How to configure a field to not be analyzed?

### ISSUE THREAD

**Issue by Hossrod** [serilog/serilog-sinks-elasticsearch#54]
Currently, I have some string fields I'm logging that show in Kibana as analyzed. Example code of how I have it setup...

```csharp
var loggerConfig = new LoggerConfiguration()
                       .MinimumLevel.Debug()
                       .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://logs:9200"))
                       {
                            AutoRegisterTemplate = true,
                            IndexFormat = "mytool-{0:yyyy.MM.dd}"
                       });
serilog = loggerConfig.CreateLogger();

string value1 = "hello";
string value2 = "world";

serilog.Information("{value1} - {value2}", value1, value2);
```

How do I make it so that `{value2}` for example is not analyzed?

Thanks!

**Comment by Hossrod** [comment]
Anyone able to help with this? This is pretty much my last hurdle. :)

Thanks!!

**Comment by mivano** [comment]
You should have a mapping (as you use the autoregistertemplate) that contains a rule for strings. Due to this, the strings are analysed, but you have a not analysed version in the .raw field. See https://github.com/serilog/serilog-sinks-elasticsearch/blob/master/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs#L166

So use value2.raw for the not analyzed version. If you want full control, then you need to pass your own template with mapping.

**Comment by Hossrod** [comment]
Thanks @mivano !

I feel dumb, but I can't get it to work. :)

I wasn't sure where to put the .raw. I tried both the below approaches I could think of, but it didn't work with either approach.
`serilog.Information("{value1} - {value2.raw}", value1, value2);` (resulted in field not being added to index)
`.ForContext("value2.raw", value2)` (resulted in field being named `value2/raw` in index and still was analyzed)

But now I'm wondering if you meant to use value2.raw when querying (like in Kibana) but couldn't see how this worked. At least not in Kibana.

Do you have an example of a custom template and how to pass it with serilog?

**Comment by mivano** [comment]
The default mapping will store the contents of value2 as fields.value2 and as fields.value2.raw (the not analysed one). So no need to change anything in serilog itself, just send {value2}. In Kibana etc you should see the additional field. See also here: https://discuss.elastic.co/t/confused-about-how-to-use-raw-fields-and-not-analyze-string-fields/28106

**Comment by Hossrod** [comment]
Thats good info thanks! I was using a custom IndexFormat, I changed `IndexFormat = "mytool-{0:yyyy.MM.dd}"` to `IndexFormat = "logstash-mytool-{0:yyyy.MM.dd}"` but it's still not making .raw versions of the fields that I can see when trying to create a visualization.

That link has some good info though. I'm new to Elasticsearch so still ramping up. From that link, looks like elasticsearch provides for a template per index based off the index name and just happens to have a default one for `logstash-*`, so I think I need to use the example someone posted in the link to create a template for `mytool-*`. This should allow me to also make strings `not_analyzed` which would be ideal I think in my use case.

One thing though, I would really like to keep the template for the tool within the tool itself. Rather than doing a PUT request manually through elasticsearch API, can I have the template (guess a string of json) in my tools code and have serilog use it when it creates the index?

**Comment by mivano** [comment]
You can do a GET to http://esname:9200/_template/serilog-events-template to get the template and see where it applies to ("template": "logstash-*"). Then you can also send this to other indexes.

**Comment by Hossrod** [comment]
Ahhh, I have an intern working on another app using Serilog-Elasticsearch and that URL returned back... `template: "AdminConsoleWebService*"`. which is the tool he is working on.

How would I create a template for `mytool-*` without overwriting `AdminConsoleWebService*`? Or do all Serilog based apps have to use the same template?

BTW, thanks again for your help and dealing with this elasticsearch and serilog noob.

**Comment by mivano** [comment]
You can get all the templates by doing a GET to http://esname:9200/_template and then look for the one that matches your index pattern. You can add multiple templates (there is an order) and they match on either index name patterns or types stored. 

Be aware that when you make changes to templates and in particular the mapping (which specifies how fields are analysed etc), then this will only impact new indexes. So in the case of the default index used by Serilog; the new daily index created will have the changed mapping.

**Comment by Hossrod** [comment]
@mivano, thank you so much for your help. I'm so sorry to keep bugging you. I just can not figure out how to make a template that gets invoked when serilog creates an index.

The tool hosting serilog is called vcptest. The IndexFormat string is `vcptest-{0:yyyy.MM.dd}`.

I keep trying different template changes to try and get all or even specific fields to not be analyzed. Each change to the template I make, I perform the following steps...

1. Kibana: delete index pattern `vcptest-*`
2. Sense: `DELETE /vcptest*`
3. Sense: `PUT /_template/vcptest` (followed by the json template I'm testing)
4. Run vcptest.exe and let it upload events, which creates an index like `vcptest-2016.07.20 `
5. Kibana: create index pattern `vcptest-*`
6. Kibana: look at index pattern and see that all string fields are still analyzed or not.

I've tried many things but just can not get strings to be `not_analyzed`. Below is latest munged up template :). The last few attempts, I gave up trying to make all strings default to `not_analyzed`, and started trying to get a specific field (`TestType`) to be `not_analyzed`, but still not working. I would prefer to not have to specify each specific field, and just have a default that all strings be `not_analyzed`.
```
PUT /_template/vcptest
{
  "order": 0,
  "template": "vcptest-*",
  "settings": {
    "index": {
      "refresh_interval": "5s"
    },
    "mappings": {
      "logevent": {
        "properties": {
          "TestType": {
            "index": "not_analyzed",
            "type": "string"
          }
        }
      },
      "_default_": {
        "dynamic_templates": [
          {
            "string_fields": {
              "mapping": {
                "index": "not_analyzed",
                "omit_norms": true,
                "type": "string"
              },
              "match_mapping_type": "string",
              "match": "*"
            }
          }
        ],
        "_all": {
          "omit_norms": true,
          "enabled": true
        },
        "properties": {
          "message": {
            "index": "analyzed",
            "type": "string"
          },
          "TestType": {
            "index": "not_analyzed",
            "type": "string"
          },
          "exceptions": {
            "type": "nested",
            "properties": {
              "ExceptionMessage": {
                "type": "object",
                "properties": {
                  "MemberType": {
                    "type": "integer"
                  }
                }
              },
              "StackTraceString": {
                "index": "analyzed",
                "type": "string"
              },
              "HResult": {
                "type": "integer"
              },
              "RemoteStackTraceString": {
                "index": "analyzed",
                "type": "string"
              },
              "RemoteStackIndex": {
                "type": "integer"
              },
              "Depth": {
                "type": "integer"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by mivano** [comment]
That is strange indeed. Do you have other templates registered (GET /_template) ? So that one based on e.g. the type is overriding? And in your above template you force all string types to be not analysed, you can make use of multifield in order to store both analysed and not analysed fields. 

Be also careful to which version of ES you run this against. There were some changes: https://www.elastic.co/guide/en/elasticsearch/reference/current/_multi_fields.html

As I do not think this is specific to the SInk, you might also be able to drop this question to a ES forum? Or maybe @Mpdreamz has some insight here?

**Comment by Hossrod** [comment]
Thanks for all your help @mivano! I got it working. In the example template I posted above, I had the message node inside the settings node by mistake! Once I moved it out, it took effect and strings are no longer analyzed.

So this works, but one thing I was wondering, is how can I include this tool specific template definition in my Visual Studio project and have have Serilog Elasticsearch upload it instead of it's built in one?

Here is updated template that is working for any future users that stumble across this...
```
PUT /_template/mytool
{
  "order": 0,
  "template": "mytool-*",
  "settings": {
    "index": {
      "refresh_interval": "5s"
    }
  },
  "mappings": {
    "_default_": {
      "dynamic_templates": [
        {
          "string_fields": {
            "mapping": {
              "index": "not_analyzed",
              "omit_norms": true,
              "type": "string"
            },
            "match_mapping_type": "string",
            "match": "*"
          }
        }
      ],
      "_all": {
        "omit_norms": true,
        "enabled": true
      },
      "properties": {
        "message": {
          "index": "analyzed",
          "type": "string"
        },
        "exceptions": {
          "type": "nested",
          "properties": {
            "ExceptionMessage": {
              "type": "object",
              "properties": {
                "MemberType": {
                  "type": "integer"
                }
              }
            },
            "StackTraceString": {
              "index": "analyzed",
              "type": "string"
            },
            "HResult": {
              "type": "integer"
            },
            "RemoteStackTraceString": {
              "index": "analyzed",
              "type": "string"
            },
            "RemoteStackIndex": {
              "type": "integer"
            },
            "Depth": {
              "type": "integer"
            }
          }
        }
      }
    }
  }
}
```

**Comment by mivano** [comment]
Good to hear. In the dev branch there is a feature that allows you to specify the template itself instead of using the default one. I will merge that one to master soon.

**Comment by mivano** [comment]
For your information; the feature you are looking for is now in master and is called GetTemplateContent on the ElasticsearchSinkOptions class. You can use this function to pass in your own template instead.

**Comment by Hossrod** [comment]
Thanks so much for your help! This whole thing making me feel stupid. :)

I nuget installed it and I see the property, but having trouble figuring out how to properly use it. Do you happen to have an example of usage? In my use case, I'm `File.ReadAllText("es_template.json"` and want to use the resulting string with `GetTemplateContent`.

**Comment by mivano** [comment]
I think you can supply an object back as a result from the function GetTemplateContent. And that object should be your template. This feature was added in this PR: https://github.com/serilog/serilog-sinks-elasticsearch/pull/51
Maybe the author @blachniet knows more?

**Comment by blachniet** [comment]
That's right, you should set `GetTemplateContent` to a function that returns either a string or a generic object. So for this example, might want to do something like the following:

```c#
var loggerConfig = new LoggerConfiguration()
                       .MinimumLevel.Debug()
                       .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://logs:9200"))
                       {
                            AutoRegisterTemplate = true,
                            IndexFormat = "mytool-{0:yyyy.MM.dd}",
                            GetTemplateContent = () => File.ReadAllText("es_template.json")
                       });
```

You can see a simple example in the [RegisterCustomTemplateTests](https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/test/Serilog.Sinks.Elasticsearch.Tests/Templating/RegisterCustomTemplateTests.cs).

**Comment by Hossrod** [comment]
Thanks so much! I made some progress with GetTemplateContent but I have a couple issues, but I'll open a separate item for it so this item can be closed.
