### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by Artur2** [serilog/serilog-sinks-elasticsearch#57]
Hi guys!
Please, rename ElasticsearchSinkOptions to ElasticSearchSinkOptions and ElasticsearchJsonFormatter
to ElasticSearchJsonFormatter. 
And one too - ElasticsearchSinkState to ElasticSearchSinkState. Or i can create PR for this.
On your decision.
Thank you!

**Comment by mivano** [comment]
The official naming convention is Elasticsearch. In the past we used ElasticSearch, from version 2 we switched to the correct name as indicated by @Mpdreamz

**Comment by Artur2** [comment]
ok, thanks.
I'll close this issue.
