### ISSUE TITLE
Custom template name when using GetTemplateContent option?

### ISSUE THREAD

**Issue by Hossrod** [serilog/serilog-sinks-elasticsearch#63]
@blachniet, #51 added the `GetTemplateContent` option which I was able to get working when `OverwriteTemplate = true`. However, the name of the template is `serilog-events-template`. I have several tools and services that will be logging with Serilog and many of them need custom templates.

Is there a way, when using `GetTemplateContent`, to specify the name of the template?

**Comment by blachniet** [comment]
Yes, set `[TemplateName](https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs#L40)` in the `ElasticsearchSinkOptions`.

**Comment by Hossrod** [comment]
Doh, sorry about that. I totally missed that option. Thanks!
