### ISSUE TITLE
Elasticsearch seems to ignore MinimumLogEventLevel

### ISSUE THREAD

**Issue by joneal** [serilog/serilog-sinks-elasticsearch#67]
I have a Serilog logger with two sinks, Elasticsearch and a custom sink (RichTextBox).

The minimum logging level for the logger is set to VERBOSE, which each sink has their level set (see below).
1. Elasticsearch - set via MinimumLogEventLevel property of ElasticSearchSinkOptions.
2. Customsink - using restrictedToMinimumLevel.

In the following configuration, the Elasticsearch sink always logs Verbose and higher, while the custom sink always correctly logs Information and higher.  How can I get the Elasticsearch sink to log Information and higher?

```
 Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Verbose()
                .WriteTo.Sink(new ElasticsearchSink(new ElasticsearchSinkOptions(new Uri(elasticsearchUrl))
                    {
                        AutoRegisterTemplate = true,
                        IndexFormat = "anduin-station-{0:yyyy.MM.dd}",
                        MinimumLogEventLevel = Serilog.Events.LogEventLevel.Information
                    }))    
                .WriteTo.TextboxLogger(control: txtOutput,
                                       restrictedToMinimumLevel: Serilog.Events.LogEventLevel.Information)
                .Enrich.FromLogContext()
                .Enrich.With(new StationNameEnricher())
                .Enrich.With(new UsernameEnricher())
                .CreateLogger();
```

Am I missing the point, or is this a bug?

**Comment by nblumhardt** [comment]
The API is a bit awkward here: the `MinimumLogEventLevel` property is only checked/respected by the `WriteTo.Elasticsearch()` method. If you pass your `ElasticSearchSinkOptions` through to it, the level filter will be applied.

(Other sinks accept this as a separate method argument, it might be worth deprecating the property on `ElasticSearchSinkOptions` in favour of the same approach here.)

**Comment by ben-foster-cko** [comment]
What about when specifying via a config file? It is also being ignored:

```
<add key="serilog:write-to:Elasticsearch.restrictedToMinimumLevel" value="Information"  />
```

**Comment by nblumhardt** [comment]
@ben-foster-cko yes, this is the same problem I believe. The `restrictedToMinimumLevel` argument is the "separate method argument" I am referring to above 👍

**Comment by mivano** [comment]
I believe we fixed this in another PR already.
