### ISSUE TITLE
Is there a way to preserve the order of log events? 

### ISSUE THREAD

**Issue by harvinders** [serilog/serilog-sinks-elasticsearch#71]
At the moment when we log events that occur very closely togeather, serilog sometimes ends up putting the  same timestamp for these events. Is there a way to preserve the order of the logs even when the timestamp is same so that we can retrieve the events in the order through kibana or NEST APIs?

See related question asked at the serilog forum https://github.com/serilog/serilog/issues/893

**Comment by mivano** [comment]
What you would want here is an auto generated id with a sequence ordering in ES. There is some reference here: https://github.com/elastic/elasticsearch/issues/10708 but never completed.

You should be able to map the _id field to an integer but I do not think you can leverage the ability of ES to generate incrementing numbers. Hope somebody else has a solution.

**Comment by Anton-L** [comment]
You can add an ID enricher to your logger configuration to sort by that ID later on:
`new LoggerConfiguration().Enrich.With<SequentialIdEnricher>().WriteTo.Logger(_logger)`

```
    /// <summary>
    /// Enrich log events with per-session sequential ID's
    /// </summary>
    public class SequentialIdEnricher : ILogEventEnricher
    {
        private long _currentId = 0;

        public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
        {
            if (logEvent == null) throw new ArgumentNullException("logEvent");

            var incrementedId = Interlocked.Increment(ref _currentId);
            logEvent.AddPropertyIfAbsent(new LogEventProperty("sequentialId", new ScalarValue(incrementedId)));
        }
    }
```

**Comment by vip32** [comment]
@Anton-L  thanks! that was exactly what i needed

**Comment by harvinders** [comment]
@Anton-L thanks for sharing. I will try it soon.

**Comment by mivano** [comment]
Nice solution, thanks. Does not generate unique increment counts in your ES index, this is per app and then even per session (lifetime of the lock on the counter), but that might cover your needs.
