### ISSUE TITLE
Not writing to all sinks with multiple elasticsearch sinks (one or the other)

### ISSUE THREAD

**Issue by tanveer-ali** [serilog/serilog-sinks-elasticsearch#73]
I found some issues when multiple elasticsearch are defined for sink

`<add key="serilog:write-to:Elasticsearch.nodeUris" value="http://localhost:9200;http://remoteurl:9200" />`

It does writes all the events but some events I see are only written in one or the another. so not duplicating events on both servers.

**Comment by tanveer-ali** [comment]
found I was not disposing the object .. after disposing like ((IDisposable)_logger).Dispose();
this is working but still there is some issues when multiple elasticsearch are defined for sink

<add key="serilog:write-to:Elasticsearch.nodeUris" value="http://localhost:9200;http://remoteurl:9200" />

It does writes all the events but some events I see are only written in one or the another. so not duplicating events on both servers.

**Comment by nblumhardt** [comment]
Thanks for the report. Have you enabled and checked [SelfLog](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics) for messages?

**Comment by tanveer-ali** [comment]
Yes I have not tried SelfLog in the start method of service like this:
  var file = File.CreateText(@"c:\logs\serilog-errors.txt");
            Serilog.Debugging.SelfLog.Enable(TextWriter.Synchronized(file));

But it's empty, there are no errors, and nothing is written into it.

**Comment by nblumhardt** [comment]
Hmm, okay, thanks for the additional info. It may need investigation by someone familiar with Elasticsearch (just helping to maintain the repo here :-))

**Comment by Moulde** [comment]
I'm not familiar with the "serilog:write-to:Elasticsearch.nodeUris" setting, so i dont know if this applies to it, but when configuring the sink fluently in code, if you want to log to multiple elasticsearch instances, you need to add multiple sinks, instead of multiple endpoints to the same sinks.
If you just add multiple endpoints, it seems it will do round robin routing of the log events.

**Comment by mivano** [comment]
That is correct. The ES sink uses the connection pool functionality. So normally you pass in a couple of endpoints and the client is clever enough to check health and connect to the available one. 

If you want to send to multiple ES clusters, then you need to add multiple sinks. Or rethink your strategy; maybe write to a file and use logstash to output it to different clusters.

**Comment by tanveer-ali** [comment]
Thanks for the information. I think I can work with single sink at the moment and if multiple sinks are needed, I can use multiple sinks.
