### ISSUE TITLE
Add support of basic authentication

### ISSUE THREAD

**Issue by agamanyuk** [serilog/serilog-sinks-elasticsearch#75]

**Comment by mivano** [comment]
Would be a good addition. You can now use the Connection property to have control over the way the connection is set up and use that to pass in your credentials.

**Comment by AmirSasson** [comment]
you can achieve this by doing:
``` 
            ElasticsearchSinkOptions options = new ElasticsearchSinkOptions(new Uri(config.ElasticUri))
            {
                IndexFormat = $"SOME-FORMAT-{0:yyyy.MM}",
                AutoRegisterTemplate = true,
                ModifyConnectionSettings = (c) => c.GlobalHeaders(new NameValueCollection { { "Authorization", "Basic TOKEN-TOKEN-TOKEN-TOKEN-" } })
            };


            loggerConfig.WriteTo.Elasticsearch(options);
```

**Comment by megakid** [comment]
Or if you want default windows credentials like we use:

    public class UseDefaultCredentialsHttpConnection : HttpConnection
    {
        protected override void SetBasicAuthenticationIfNeeded(HttpWebRequest request, RequestData requestData)
        {
            // Do nothing
        }

        protected override HttpWebRequest CreateWebRequest(RequestData requestData)
        {
            var request = base.CreateWebRequest(requestData);

            // Enable kerberos auths 
            request.PreAuthenticate = true;
            request.UseDefaultCredentials = true;

            return request;
        }
    }

    var elasticOptions = new ElasticsearchSinkOptions(_uri)
    {
        Connection = new UseDefaultCredentialsHttpConnection(),
        ModifyConnectionSettings = c => c.EnableHttpCompression(), // Not needed for Auth but shows what else can be done
    };
