### ISSUE TITLE
Add support for pipelines

### ISSUE THREAD

**Issue by srogovtsev** [serilog/serilog-sinks-elasticsearch#78]
I'd like to be able to specify [pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html) while ingesting events into ES. From what I see this can be done quite easily by specifying a `BulkRequestParameters.Pipeline` option in `requestParameters` configurator parameter in `Bulk` method.

**Comment by mivano** [comment]
Certainly a nice feature, although be aware that the amount of data coming from an application to ES can be high. For some use cases it might be easier/better to use something like logstash in between. 

You have something in mind for a PR?

**Comment by ajviradia** [comment]
Please look at PR "Added support for Pipeline in Elasticsearch sink options #124" in this reference. 

Added optional parameter "PipelineName" for ElasticsearchSinkOptions to specify if you want to leverage pipeline in Elasticsearch while sending messages to it. 

Note: Pipeline must be present  in Elasticsearch.

@mivano, can you merge this PR? Thanks.

**Comment by mivano** [comment]
Merged! thanks
