### ISSUE TITLE
How do I configure this sink to ignore SSL errors?

### ISSUE THREAD

**Issue by jamesla** [serilog/serilog-sinks-elasticsearch#83]
How do I configure this sink to ignore SSL errors?

something similar to curl's -K parameter

**Comment by mivano** [comment]
You can use a trick like this:

```csharp
  ServicePointManager.ServerCertificateValidationCallback =
                    (source, certificate, chain, sslPolicyErrors) => true;
```

All validation of certificates get overridden and a true is returned. Do not use on production :-)

**Comment by jamesla** [comment]
worked thanks

**Comment by Mpdreamz** [comment]
> Do not use on production :-)

👍 @mivano 

You can be a tad more selective in what you trust through that callback we documented it here:

https://www.elastic.co/guide/en/elasticsearch/client/net-api/1.x/security.html#trusting-certifcate-example
