### ISSUE TITLE
Connection error logs

### ISSUE THREAD

**Issue by jamesla** [serilog/serilog-sinks-elasticsearch#84]
I'm having trouble getting this to connect to my elastic search over https. The certificate is installed correctly however I'm wondering if there is a certificate chain error. 

How can I view the output of this sink's failed connection attempts?

**Comment by mivano** [comment]
Have a look here https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics to enable the selflog. The sink will write to this selflog.

**Comment by jamesla** [comment]
perfect thanks
