### ISSUE TITLE
Serilog elasticsearch sink only works from a controller

### ISSUE THREAD

**Issue by hakonn** [serilog/serilog-sinks-elasticsearch#86]
A couple of weeks ago I installed ELK and everything seemed to work fine. I have a web application with serilog and the elasticsearch sink, everything is working fine when I'm logging from a controller. 

I'm using the latest packages. 

However, when I tried to log from a console application it didn't work. Then I tried to log from a unit test in my web project and it din't work either.

How can this be? 

I looked at the web requests in fiddler and found that when I log from the unit test it sends an "empty" request to elastic to this url: /_template/serilog-events-template

This also happens when I log from the controller in the web project, but the web project also sends another request right afterwards, /bulk, which contains the error message. 

Here is an example:

`var url = ConfigurationManager.AppSettings["Logger.Url"];
var obj = new Test() { Name = "MyName", Phone = "123456789" };
var messageTemplate = "This is a test {@obj}";
var exception = new Exception("Exception test");

var loggerConfig = new LoggerConfiguration()
      .MinimumLevel.Debug()
       .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri(url))
        {
             AutoRegisterTemplate = true,
        });

var logger = loggerConfig.CreateLogger();   
logger.Error(exception, messageTemplate, obj);`

Any suggestions?

**Comment by nblumhardt** [comment]
You need to dispose the logger when the application/test exits. Cheers!

**Comment by hakonn** [comment]
Yes of course. I should have thought of that. Thank you very much!
