### ISSUE TITLE
specify Authorization header in configuration

### ISSUE THREAD

**Issue by AmirSasson** [serilog/serilog-sinks-elasticsearch#87]
i am using the Serilog.Configuration to configure my serilog, and i am writing my logs to Elastic search.
my ElasticSearch instance requires  Bearer Token in the Authorization Header.
at the moment there is no way specifying the Authorization header in the web/app.config file.
only pragmatically by specifying : ModifyConnectionSettings.

**Comment by mivano** [comment]
Correct, there is no overload that you can use for this as it requires some pretty specific code to support this authentication. Do you have an solution in mind?

**Comment by AmirSasson** [comment]
maybe implement something that will support
`<add key="serilog:write-to:Elasticsearch.connectionGlobalHeaders" value="Authorization=SOMETOKEN&SOME-OTHER-HEADER=SOME-OTHER-VALUE" />`

deserialize the the **value** into key value pair and add global headers this way:
 ModifyConnectionSettings = (c) => c.GlobalHeaders(new NameValueCollection { { "Authorization", config.ESLogsAuthToken } })

does this make sense?
