### ISSUE TITLE
How do you guys handle different data types for the same field when logging?

### ISSUE THREAD

**Issue by christiansparre** [serilog/serilog-sinks-elasticsearch#88]
Hi, we have been evaluating elasticsearch a number of times but never really made the jump. I keep running into issues with the field types that are automatically registered when using elasticsearch for logging.

Field types get registered the first time serilog sends that field to elasticsearch and if you later happen to send that field with another type the event is not indexed.

We would run into this quite often I fear as logging, at least the way we do it, is quite dynamic and we do not impose strict rules/review on the type of the fields we choose to include in log events.

So I wanted to ask how others are overcoming this when using serilog and elasticsearch?

**Comment by mivano** [comment]
The sink will register a template which will match your index name (default logstash-*). Part of this template is a mapping that will correct most of the fields for you. But when you send something like fields.A as a string and then as an object it will not work/parse. 

Have a look here for the default template: https://github.com/serilog/serilog-sinks-elasticsearch/blob/dev/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs#L145

**Comment by christiansparre** [comment]
Thanks Michiel, I am aware of how Serilog registers the template, I have been playing around with custom ones.

What I was looking for was how you approach the parse error if you try to index an object into field.A if that field has been automatically registered as a string. I would think theses problems occur from time to time when using elasticsearch for logging. 

Everyone seems to praise it for logging use cases, but it seems very hard to actually use it for anything as dynamic in nature as logs from Serilog, if you do not impose very strict rules on the types of the properties you emit in your events. I might be wrongs, so I'm looking for others who have experience with it.

**Comment by mivano** [comment]
Yes a valid concern. We have some discussions about that before; what to do when Elasticsearch rejects the logevent as it cannot parse it. There are some ways to capture this and handle it but still, you cannot store it in ES. 

So general rule is to keep unique names, I did see somebody created a custom serializer that adds more uniqueness to the property names based on the types.
