### ISSUE TITLE
ASP.NET Web Api stops emitting to Elasticsearch

### ISSUE THREAD

**Issue by redwhat** [serilog/serilog-sinks-elasticsearch#91]
We have a ASP.NET Web Api application that uses Serilog with the Elasticsearch sink. It is configured for durability and the buffer continues to fill but the push to Elasticsearch freezes shortly after the application starts. It is running under IIS and a restart of the AppPool clears the buffer into Elasticsearch. A review of the sink's source indicates that the ElasticSearchLogShipper OnTick() handler handles both the persistence to the durable log file and transport to Elasticsearch. It must fire but we've been unable to determine why it does not get forwarded to Elasticsearch.

**Comment by dlyson** [comment]
I've seen a similar issue. My app was deployed to Azure. The web app was scaled to 4 instances. All of them used a single file share. Many processes tried to write to buffer with the same name and the RollingFile sink created files like "MyWebApp-20170322.json", "MyWebApp-20170322-001.json", etc. Unfortunately the Elasticsearch sink used a single bookmark file to track what was sent to Elasticsearch. As a result logs were sent only from the last buffer (if the bookmark file was not corrupted). If the app was restarted then first few buffer files were just deleted (without sending to Elasticsearch).
My solution was to add the hostname to the buffer file name. It would be good to secure that scenario:
- detect this situation and throw exception / self log anything
- support many booking files
- add hostname / process id to the file name by default

**Comment by mivano** [comment]
Provided options sound good for documentation purposes. Closing issue for now.
