### ISSUE TITLE
Support for elasticsearch 5.x

### ISSUE THREAD

**Issue by Skaanning** [serilog/serilog-sinks-elasticsearch#92]
Hi.
Is there any on-going plans for supporting version 5.x of elasticsearch? 
If not, is there any workaround i can use so this sink can work with elasticsearch-net 5.0?

**Comment by Skaanning** [comment]
bindingRedirect of Elasticsearch.net from over versions to 5.0 seems to work just fine. 
So i guess this is not really an issue.

**Comment by ffMathy** [comment]
It would still make sense to update the support, especially for projects that rely on other COM projects.

**Comment by mivano** [comment]
The current implementation does work against a v5 of ES as it uses pretty basic API calls. It makes sense to upgrade to the latest elasticsearch client too. Care for a PR?

**Comment by ffMathy** [comment]
I tried, but the project uses the old project.json format and I don't know how to convert away from that. 

It is not used anymore and it makes my Visual Studio confused.

**Comment by ffMathy** [comment]
@mivano could you look at switching to `.csproj`? Then I can work on this task, and so can many other people who use VS2017.

**Comment by mivano** [comment]
I have no objection switching to the _new_ format. Unfortunately I do not have the time available.

**Comment by ffMathy** [comment]
Finally got time to do both the format stuff and the NuGet stuff in #109. Could you take a look?

**Comment by mivano** [comment]
All merged to master. Thanks!
