### ISSUE TITLE
Question - Possible to use a CustomFormatter *and* app settings?

### ISSUE THREAD

**Issue by dahlsailrunner** [serilog/serilog-sinks-elasticsearch#95]
I was wondering if it's possible to specify a CustomFormatter and use app settings configuration for the Elasticsearch sink.

All of the other options I'm after are available via appSettings - but the CustomFormatter doesn't appear to be.  I'm just wondering if there is any way to use a custom formatter while keeping the config within app settings.

Thanks in advance.
-Erik

**Comment by mivano** [comment]
No sorry, at the moment only the simple types are supported. You will need to write some startup logic and read your own settings and construct the right logger out of that.

**Comment by dahlsailrunner** [comment]
Cool -- that's what I thought -- just wanted to make sure I wasn't missing anything.  Thanks for your quick response!  :)
