### ISSUE TITLE
Docs not up-to-date?

### ISSUE THREAD

**Issue by DinoSourcesRex** [serilog/serilog-sinks-elasticsearch#98]
Hi,

So I see that there's a 5.0 on nuget for this sink but I can't find any information on what is on 5.0 here, nor what the breaking changes are.

Am I just not looking in the right place? Having the releases section up-to-date would be very helpful as well.

**Comment by mivano** [comment]
Please have a look at this: https://github.com/serilog/serilog-sinks-elasticsearch/blob/master/CHANGES.md

**Comment by DinoSourcesRex** [comment]
There you go. Thanks @mivano. Consider this closed, though I stand by a releases section being useful!

**Comment by mivano** [comment]
I agree with you and was trying to link this up in the appveyor build so it would write it as a release but did not succeed yet. I will keep trying.

**Comment by DinoSourcesRex** [comment]
Very good. I should have really checked the solution for the changes file but I honestly didn't even think to look there. My question is answered though so I'm a happy man.

Keep up the great work!
